<?php

/**
 * BasepartenaireLogo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $partenaire_id
 * @property string $src
 * @property string $href
 * @property partenaire $partenaire
 * 
 * @method integer        getId()            Returns the current record's "id" value
 * @method integer        getPartenaireId()  Returns the current record's "partenaire_id" value
 * @method string         getSrc()           Returns the current record's "src" value
 * @method string         getHref()          Returns the current record's "href" value
 * @method partenaire     getPartenaire()    Returns the current record's "partenaire" value
 * @method partenaireLogo setId()            Sets the current record's "id" value
 * @method partenaireLogo setPartenaireId()  Sets the current record's "partenaire_id" value
 * @method partenaireLogo setSrc()           Sets the current record's "src" value
 * @method partenaireLogo setHref()          Sets the current record's "href" value
 * @method partenaireLogo setPartenaire()    Sets the current record's "partenaire" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasepartenaireLogo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('partenaire_logo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('partenaire_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('src', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('href', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('partenaire', array(
             'local' => 'partenaire_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}