<?php

/**
 * Basefilleul
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $user_id
 * @property bigint $filleul_id
 * @property string $email_address
 * @property sfGuardUser $Parrain
 * @property sfGuardUser $Filleul
 * 
 * @method bigint      getUserId()        Returns the current record's "user_id" value
 * @method bigint      getFilleulId()     Returns the current record's "filleul_id" value
 * @method string      getEmailAddress()  Returns the current record's "email_address" value
 * @method sfGuardUser getParrain()       Returns the current record's "Parrain" value
 * @method sfGuardUser getFilleul()       Returns the current record's "Filleul" value
 * @method filleul     setUserId()        Sets the current record's "user_id" value
 * @method filleul     setFilleulId()     Sets the current record's "filleul_id" value
 * @method filleul     setEmailAddress()  Sets the current record's "email_address" value
 * @method filleul     setParrain()       Sets the current record's "Parrain" value
 * @method filleul     setFilleul()       Sets the current record's "Filleul" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basefilleul extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('filleul');
        $this->hasColumn('user_id', 'bigint', 20, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('filleul_id', 'bigint', 20, array(
             'type' => 'bigint',
             'unique' => true,
             'length' => 20,
             ));
        $this->hasColumn('email_address', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Parrain', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as Filleul', array(
             'local' => 'filleul_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}