<?php

/**
 * Basemodule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $content_id
 * @property enum $content_type
 * @property boolean $is_active
 * @property string $action
 * @property string $user_access
 * @property Doctrine_Collection $content
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getContentId()    Returns the current record's "content_id" value
 * @method enum                getContentType()  Returns the current record's "content_type" value
 * @method boolean             getIsActive()     Returns the current record's "is_active" value
 * @method string              getAction()       Returns the current record's "action" value
 * @method string              getUserAccess()   Returns the current record's "user_access" value
 * @method Doctrine_Collection getContent()      Returns the current record's "content" collection
 * @method module              setId()           Sets the current record's "id" value
 * @method module              setContentId()    Sets the current record's "content_id" value
 * @method module              setContentType()  Sets the current record's "content_type" value
 * @method module              setIsActive()     Sets the current record's "is_active" value
 * @method module              setAction()       Sets the current record's "action" value
 * @method module              setUserAccess()   Sets the current record's "user_access" value
 * @method module              setContent()      Sets the current record's "content" collection
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basemodule extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('module');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('content_id', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('content_type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'category',
              1 => 'lien',
              2 => 'article',
              3 => 'newsletter',
              4 => 'programme',
              5 => 'organisme',
              6 => 'gmap',
              7 => 'recherche',
              8 => 'user',
              9 => 'sgGuardAuth',
             ),
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('action', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('user_access', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('content', array(
             'local' => 'id',
             'foreign' => 'module_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}