<?php

/**
 * BaseuserCoupon
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $user_id
 * @property integer $coupon_id
 * @property sfGuardUser $User
 * @property coupon $coupon
 * 
 * @method bigint      getUserId()    Returns the current record's "user_id" value
 * @method integer     getCouponId()  Returns the current record's "coupon_id" value
 * @method sfGuardUser getUser()      Returns the current record's "User" value
 * @method coupon      getCoupon()    Returns the current record's "coupon" value
 * @method userCoupon  setUserId()    Sets the current record's "user_id" value
 * @method userCoupon  setCouponId()  Sets the current record's "coupon_id" value
 * @method userCoupon  setUser()      Sets the current record's "User" value
 * @method userCoupon  setCoupon()    Sets the current record's "coupon" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseuserCoupon extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_coupon');
        $this->hasColumn('user_id', 'bigint', 20, array(
             'type' => 'bigint',
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('coupon_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('coupon', array(
             'local' => 'coupon_id',
             'foreign' => 'id'));
    }
}