<?php

/**
 * BaselogCoupon
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $ip
 * @property string $email
 * @property integer $coupon_id
 * @property boolean $is_newsletter
 * @property coupon $coupon
 * 
 * @method integer   getId()            Returns the current record's "id" value
 * @method string    getIp()            Returns the current record's "ip" value
 * @method string    getEmail()         Returns the current record's "email" value
 * @method integer   getCouponId()      Returns the current record's "coupon_id" value
 * @method boolean   getIsNewsletter()  Returns the current record's "is_newsletter" value
 * @method coupon    getCoupon()        Returns the current record's "coupon" value
 * @method logCoupon setId()            Sets the current record's "id" value
 * @method logCoupon setIp()            Sets the current record's "ip" value
 * @method logCoupon setEmail()         Sets the current record's "email" value
 * @method logCoupon setCouponId()      Sets the current record's "coupon_id" value
 * @method logCoupon setIsNewsletter()  Sets the current record's "is_newsletter" value
 * @method logCoupon setCoupon()        Sets the current record's "coupon" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaselogCoupon extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('log_coupon');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('ip', 'string', 15, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 15,
             ));
        $this->hasColumn('email', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('coupon_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             'length' => 4,
             ));
        $this->hasColumn('is_newsletter', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('coupon', array(
             'local' => 'coupon_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}