<?php

/**
 * BaseaffiliatePlateforme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $unique_name
 * @property Doctrine_Collection $Affiliates
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getUniqueName()  Returns the current record's "unique_name" value
 * @method Doctrine_Collection getAffiliates()  Returns the current record's "Affiliates" collection
 * @method affiliatePlateforme setId()          Sets the current record's "id" value
 * @method affiliatePlateforme setUniqueName()  Sets the current record's "unique_name" value
 * @method affiliatePlateforme setAffiliates()  Sets the current record's "Affiliates" collection
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseaffiliatePlateforme extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('affiliate_plateforme');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('unique_name', 'string', 30, array(
             'type' => 'string',
             'unique' => true,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('engine as Affiliates', array(
             'local' => 'id',
             'foreign' => 'id_plateforme'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}