<?php

/**
 * Basetree
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $programme_id
 * @property programme $Programme
 * @property Doctrine_Collection $treeUser
 * @property Doctrine_Collection $treeCoupon
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method integer             getProgrammeId()  Returns the current record's "programme_id" value
 * @method programme           getProgramme()    Returns the current record's "Programme" value
 * @method Doctrine_Collection getTreeUser()     Returns the current record's "treeUser" collection
 * @method Doctrine_Collection getTreeCoupon()   Returns the current record's "treeCoupon" collection
 * @method tree                setId()           Sets the current record's "id" value
 * @method tree                setProgrammeId()  Sets the current record's "programme_id" value
 * @method tree                setProgramme()    Sets the current record's "Programme" value
 * @method tree                setTreeUser()     Sets the current record's "treeUser" collection
 * @method tree                setTreeCoupon()   Sets the current record's "treeCoupon" collection
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basetree extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tree');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('programme_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('programme as Programme', array(
             'local' => 'programme_id',
             'foreign' => 'id'));

        $this->hasMany('treeUser', array(
             'local' => 'id',
             'foreign' => 'tree_id'));

        $this->hasMany('treeCoupon', array(
             'local' => 'id',
             'foreign' => 'tree_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}