<?php

/**
 * Basecategorie
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $parent_id
 * @property boolean $is_active
 * @property Doctrine_Collection $lien_categorie
 * @property Doctrine_Collection $article_categorie
 * @property Doctrine_Collection $newsletter_categorie
 * 
 * @method integer             getId()                   Returns the current record's "id" value
 * @method string              getName()                 Returns the current record's "name" value
 * @method integer             getParentId()             Returns the current record's "parent_id" value
 * @method boolean             getIsActive()             Returns the current record's "is_active" value
 * @method Doctrine_Collection getLienCategorie()        Returns the current record's "lien_categorie" collection
 * @method Doctrine_Collection getArticleCategorie()     Returns the current record's "article_categorie" collection
 * @method Doctrine_Collection getNewsletterCategorie()  Returns the current record's "newsletter_categorie" collection
 * @method categorie           setId()                   Sets the current record's "id" value
 * @method categorie           setName()                 Sets the current record's "name" value
 * @method categorie           setParentId()             Sets the current record's "parent_id" value
 * @method categorie           setIsActive()             Sets the current record's "is_active" value
 * @method categorie           setLienCategorie()        Sets the current record's "lien_categorie" collection
 * @method categorie           setArticleCategorie()     Sets the current record's "article_categorie" collection
 * @method categorie           setNewsletterCategorie()  Sets the current record's "newsletter_categorie" collection
 * 
 * @package    up2green
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecategorie extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('categorie');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('parent_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('lien_categorie', array(
             'local' => 'id',
             'foreign' => 'categorie_id'));

        $this->hasMany('article_categorie', array(
             'local' => 'id',
             'foreign' => 'categorie_id'));

        $this->hasMany('newsletter_categorie', array(
             'local' => 'id',
             'foreign' => 'categorie_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $sluggable1 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'uniqueBy' => 
             array(
              0 => 'lang',
              1 => 'name',
             ),
             ));
        $i18n0->addChild($sluggable1);
        $this->actAs($i18n0);
    }
}