<?php

/**
 * BaseuserTree
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $user_id
 * @property integer $tree_id
 * @property sfGuardUser $User
 * @property tree $tree
 * 
 * @method bigint      getUserId()  Returns the current record's "user_id" value
 * @method integer     getTreeId()  Returns the current record's "tree_id" value
 * @method sfGuardUser getUser()    Returns the current record's "User" value
 * @method tree        getTree()    Returns the current record's "tree" value
 * @method userTree    setUserId()  Sets the current record's "user_id" value
 * @method userTree    setTreeId()  Sets the current record's "tree_id" value
 * @method userTree    setUser()    Sets the current record's "User" value
 * @method userTree    setTree()    Sets the current record's "tree" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseuserTree extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_tree');
        $this->hasColumn('user_id', 'bigint', 20, array(
             'type' => 'bigint',
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('tree_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('tree', array(
             'local' => 'tree_id',
             'foreign' => 'id'));
    }
}