<?php

/**
 * Baseprofil
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property bigint $user_id
 * @property float $credit
 * @property integer $is_newsletter
 * @property string $culture
 * @property sfGuardUser $User
 * 
 * @method integer     getId()            Returns the current record's "id" value
 * @method bigint      getUserId()        Returns the current record's "user_id" value
 * @method float       getCredit()        Returns the current record's "credit" value
 * @method integer     getIsNewsletter()  Returns the current record's "is_newsletter" value
 * @method string      getCulture()       Returns the current record's "culture" value
 * @method sfGuardUser getUser()          Returns the current record's "User" value
 * @method profil      setId()            Sets the current record's "id" value
 * @method profil      setUserId()        Sets the current record's "user_id" value
 * @method profil      setCredit()        Sets the current record's "credit" value
 * @method profil      setIsNewsletter()  Sets the current record's "is_newsletter" value
 * @method profil      setCulture()       Sets the current record's "culture" value
 * @method profil      setUser()          Sets the current record's "User" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseprofil extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profil');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'bigint', 20, array(
             'type' => 'bigint',
             'notnull' => true,
             'unique' => true,
             'length' => 20,
             ));
        $this->hasColumn('credit', 'float', 18, array(
             'type' => 'float',
             'notnull' => true,
             'default' => 0,
             'length' => 18,
             'scale' => '4',
             ));
        $this->hasColumn('is_newsletter', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'length' => 1,
             ));
        $this->hasColumn('culture', 'string', 7, array(
             'type' => 'string',
             'default' => 'fr_FR',
             'length' => 7,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}