<?php

/**
 * BasepartenaireProgramme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $partenaire_id
 * @property integer $programme_id
 * @property integer $number
 * @property integer $hardcode
 * @property partenaire $partenaire
 * @property programme $programme
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method integer             getPartenaireId()  Returns the current record's "partenaire_id" value
 * @method integer             getProgrammeId()   Returns the current record's "programme_id" value
 * @method integer             getNumber()        Returns the current record's "number" value
 * @method integer             getHardcode()      Returns the current record's "hardcode" value
 * @method partenaire          getPartenaire()    Returns the current record's "partenaire" value
 * @method programme           getProgramme()     Returns the current record's "programme" value
 * @method partenaireProgramme setId()            Sets the current record's "id" value
 * @method partenaireProgramme setPartenaireId()  Sets the current record's "partenaire_id" value
 * @method partenaireProgramme setProgrammeId()   Sets the current record's "programme_id" value
 * @method partenaireProgramme setNumber()        Sets the current record's "number" value
 * @method partenaireProgramme setHardcode()      Sets the current record's "hardcode" value
 * @method partenaireProgramme setPartenaire()    Sets the current record's "partenaire" value
 * @method partenaireProgramme setProgramme()     Sets the current record's "programme" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasepartenaireProgramme extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('partenaire_programme');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('partenaire_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('programme_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('number', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             ));
        $this->hasColumn('hardcode', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('partenaire', array(
             'local' => 'partenaire_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('programme', array(
             'local' => 'programme_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}