<?php

/**
 * BaseorganismePoint
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $organisme_id
 * @property organisme $Organisme
 * 
 * @method integer        getOrganismeId()  Returns the current record's "organisme_id" value
 * @method organisme      getOrganisme()    Returns the current record's "Organisme" value
 * @method organismePoint setOrganismeId()  Sets the current record's "organisme_id" value
 * @method organismePoint setOrganisme()    Sets the current record's "Organisme" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseorganismePoint extends point
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('organisme_point');
        $this->hasColumn('organisme_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('organisme as Organisme', array(
             'local' => 'organisme_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}