<?php

/**
 * BaselienCategorie
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $categorie_id
 * @property integer $lien_id
 * @property categorie $categorie
 * @property lien $lien
 * 
 * @method integer       getCategorieId()  Returns the current record's "categorie_id" value
 * @method integer       getLienId()       Returns the current record's "lien_id" value
 * @method categorie     getCategorie()    Returns the current record's "categorie" value
 * @method lien          getLien()         Returns the current record's "lien" value
 * @method lienCategorie setCategorieId()  Sets the current record's "categorie_id" value
 * @method lienCategorie setLienId()       Sets the current record's "lien_id" value
 * @method lienCategorie setCategorie()    Sets the current record's "categorie" value
 * @method lienCategorie setLien()         Sets the current record's "lien" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaselienCategorie extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lien_categorie');
        $this->hasColumn('categorie_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('lien_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('categorie', array(
             'local' => 'categorie_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('lien', array(
             'local' => 'lien_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}