<?php

/**
 * BasemailingList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $email_address
 * @property boolean $is_newsletter
 * 
 * @method string      getEmailAddress()  Returns the current record's "email_address" value
 * @method boolean     getIsNewsletter()  Returns the current record's "is_newsletter" value
 * @method mailingList setEmailAddress()  Sets the current record's "email_address" value
 * @method mailingList setIsNewsletter()  Sets the current record's "is_newsletter" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemailingList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mailing_list');
        $this->hasColumn('email_address', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_newsletter', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}