<?php

/**
 * BaselienCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $lien_id
 * @property category $category
 * @property lien $lien
 * 
 * @method integer      getCategoryId()  Returns the current record's "category_id" value
 * @method integer      getLienId()      Returns the current record's "lien_id" value
 * @method category     getCategory()    Returns the current record's "category" value
 * @method lien         getLien()        Returns the current record's "lien" value
 * @method lienCategory setCategoryId()  Sets the current record's "category_id" value
 * @method lienCategory setLienId()      Sets the current record's "lien_id" value
 * @method lienCategory setCategory()    Sets the current record's "category" value
 * @method lienCategory setLien()        Sets the current record's "lien" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaselienCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lien_category');
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('lien_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('lien', array(
             'local' => 'lien_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}