<?php

/**
 * BaseprogrammePoint
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $programme_id
 * @property programme $Programme
 * 
 * @method integer        getProgrammeId()  Returns the current record's "programme_id" value
 * @method programme      getProgramme()    Returns the current record's "Programme" value
 * @method programmePoint setProgrammeId()  Sets the current record's "programme_id" value
 * @method programmePoint setProgramme()    Sets the current record's "Programme" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseprogrammePoint extends point
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('programme_point');
        $this->hasColumn('programme_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('programme as Programme', array(
             'local' => 'programme_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}