<?php

/**
 * Basetree
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $programme_id
 * @property programme $Programme
 * @property treeCoupon $Coupon
 * @property treeUser $User
 * 
 * @method integer    getId()           Returns the current record's "id" value
 * @method integer    getProgrammeId()  Returns the current record's "programme_id" value
 * @method programme  getProgramme()    Returns the current record's "Programme" value
 * @method treeCoupon getCoupon()       Returns the current record's "Coupon" value
 * @method treeUser   getUser()         Returns the current record's "User" value
 * @method tree       setId()           Sets the current record's "id" value
 * @method tree       setProgrammeId()  Sets the current record's "programme_id" value
 * @method tree       setProgramme()    Sets the current record's "Programme" value
 * @method tree       setCoupon()       Sets the current record's "Coupon" value
 * @method tree       setUser()         Sets the current record's "User" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basetree extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tree');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('programme_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('programme as Programme', array(
             'local' => 'programme_id',
             'foreign' => 'id'));

        $this->hasOne('treeCoupon as Coupon', array(
             'local' => 'id',
             'foreign' => 'tree_id'));

        $this->hasOne('treeUser as User', array(
             'local' => 'id',
             'foreign' => 'tree_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}