<?php

/**
 * BasecouponPartenaire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $coupon_id
 * @property integer $partenaire_id
 * @property partenaire $partenaire
 * @property coupon $coupon
 * 
 * @method integer          getCouponId()      Returns the current record's "coupon_id" value
 * @method integer          getPartenaireId()  Returns the current record's "partenaire_id" value
 * @method partenaire       getPartenaire()    Returns the current record's "partenaire" value
 * @method coupon           getCoupon()        Returns the current record's "coupon" value
 * @method couponPartenaire setCouponId()      Sets the current record's "coupon_id" value
 * @method couponPartenaire setPartenaireId()  Sets the current record's "partenaire_id" value
 * @method couponPartenaire setPartenaire()    Sets the current record's "partenaire" value
 * @method couponPartenaire setCoupon()        Sets the current record's "coupon" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasecouponPartenaire extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('coupon_partenaire');
        $this->hasColumn('coupon_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('partenaire_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('partenaire', array(
             'local' => 'partenaire_id',
             'foreign' => 'id'));

        $this->hasOne('coupon', array(
             'local' => 'coupon_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}