<?php

/**
 * Basesession
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $sess_id
 * @property clob $sess_data
 * @property integer $sess_time
 * @property boolean $is_authenticated
 * @property integer $last_request_time
 * @property integer $user_id
 * @property string $app
 * @property string $module
 * @property string $action
 * @property boolean $is_ajax
 * @property string $ip
 * @property string $culture
 * @property string $user_agent
 * 
 * @method string  getSessId()            Returns the current record's "sess_id" value
 * @method clob    getSessData()          Returns the current record's "sess_data" value
 * @method integer getSessTime()          Returns the current record's "sess_time" value
 * @method boolean getIsAuthenticated()   Returns the current record's "is_authenticated" value
 * @method integer getLastRequestTime()   Returns the current record's "last_request_time" value
 * @method integer getUserId()            Returns the current record's "user_id" value
 * @method string  getApp()               Returns the current record's "app" value
 * @method string  getModule()            Returns the current record's "module" value
 * @method string  getAction()            Returns the current record's "action" value
 * @method boolean getIsAjax()            Returns the current record's "is_ajax" value
 * @method string  getIp()                Returns the current record's "ip" value
 * @method string  getCulture()           Returns the current record's "culture" value
 * @method string  getUserAgent()         Returns the current record's "user_agent" value
 * @method session setSessId()            Sets the current record's "sess_id" value
 * @method session setSessData()          Sets the current record's "sess_data" value
 * @method session setSessTime()          Sets the current record's "sess_time" value
 * @method session setIsAuthenticated()   Sets the current record's "is_authenticated" value
 * @method session setLastRequestTime()   Sets the current record's "last_request_time" value
 * @method session setUserId()            Sets the current record's "user_id" value
 * @method session setApp()               Sets the current record's "app" value
 * @method session setModule()            Sets the current record's "module" value
 * @method session setAction()            Sets the current record's "action" value
 * @method session setIsAjax()            Sets the current record's "is_ajax" value
 * @method session setIp()                Sets the current record's "ip" value
 * @method session setCulture()           Sets the current record's "culture" value
 * @method session setUserAgent()         Sets the current record's "user_agent" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basesession extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('session');
        $this->hasColumn('sess_id', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             'primary' => true,
             ));
        $this->hasColumn('sess_data', 'clob', 65532, array(
             'type' => 'clob',
             'length' => 65532,
             'notnull' => true,
             ));
        $this->hasColumn('sess_time', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('is_authenticated', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('last_request_time', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('app', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('module', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('action', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_ajax', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('ip', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('culture', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('user_agent', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}