<?php

/**
 * BasearticleCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $article_id
 * @property category $category
 * @property article $article
 * 
 * @method integer         getCategoryId()  Returns the current record's "category_id" value
 * @method integer         getArticleId()   Returns the current record's "article_id" value
 * @method category        getCategory()    Returns the current record's "category" value
 * @method article         getArticle()     Returns the current record's "article" value
 * @method articleCategory setCategoryId()  Sets the current record's "category_id" value
 * @method articleCategory setArticleId()   Sets the current record's "article_id" value
 * @method articleCategory setCategory()    Sets the current record's "category" value
 * @method articleCategory setArticle()     Sets the current record's "article" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasearticleCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article_category');
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('article_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('article', array(
             'local' => 'article_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}