<?php

/**
 * BasetreeCoupon
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tree_id
 * @property integer $coupon_id
 * @property tree $tree
 * @property coupon $coupon
 * 
 * @method integer    getTreeId()    Returns the current record's "tree_id" value
 * @method integer    getCouponId()  Returns the current record's "coupon_id" value
 * @method tree       getTree()      Returns the current record's "tree" value
 * @method coupon     getCoupon()    Returns the current record's "coupon" value
 * @method treeCoupon setTreeId()    Sets the current record's "tree_id" value
 * @method treeCoupon setCouponId()  Sets the current record's "coupon_id" value
 * @method treeCoupon setTree()      Sets the current record's "tree" value
 * @method treeCoupon setCoupon()    Sets the current record's "coupon" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetreeCoupon extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tree_coupon');
        $this->hasColumn('tree_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('coupon_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('tree', array(
             'local' => 'tree_id',
             'foreign' => 'id'));

        $this->hasOne('coupon', array(
             'local' => 'coupon_id',
             'foreign' => 'id'));
    }
}