<?php

/**
 * BaseuserCoupon
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $coupon_id
 * @property sfGuardUser $sfGuardUser
 * @property coupon $coupon
 * 
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method integer     getCouponId()    Returns the current record's "coupon_id" value
 * @method sfGuardUser getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method coupon      getCoupon()      Returns the current record's "coupon" value
 * @method userCoupon  setUserId()      Sets the current record's "user_id" value
 * @method userCoupon  setCouponId()    Sets the current record's "coupon_id" value
 * @method userCoupon  setSfGuardUser() Sets the current record's "sfGuardUser" value
 * @method userCoupon  setCoupon()      Sets the current record's "coupon" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseuserCoupon extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_coupon');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('coupon_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('coupon', array(
             'local' => 'coupon_id',
             'foreign' => 'id'));
    }
}