<?php

/**
 * BaseuserTree
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $tree_id
 * @property sfGuardUser $sfGuardUser
 * @property tree $tree
 * 
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method integer     getTreeId()      Returns the current record's "tree_id" value
 * @method sfGuardUser getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method tree        getTree()        Returns the current record's "tree" value
 * @method userTree    setUserId()      Sets the current record's "user_id" value
 * @method userTree    setTreeId()      Sets the current record's "tree_id" value
 * @method userTree    setSfGuardUser() Sets the current record's "sfGuardUser" value
 * @method userTree    setTree()        Sets the current record's "tree" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseuserTree extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_tree');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('tree_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('tree', array(
             'local' => 'tree_id',
             'foreign' => 'id'));
    }
}