<?php

/**
 * Basecategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $unique_name
 * @property integer $rank
 * @property boolean $is_active
 * @property Doctrine_Collection $Articles
 * @property Doctrine_Collection $Newsletters
 * @property Doctrine_Collection $Liens
 * @property Doctrine_Collection $Affiliates
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getUniqueName()  Returns the current record's "unique_name" value
 * @method integer             getRank()        Returns the current record's "rank" value
 * @method boolean             getIsActive()    Returns the current record's "is_active" value
 * @method Doctrine_Collection getArticles()    Returns the current record's "Articles" collection
 * @method Doctrine_Collection getNewsletters() Returns the current record's "Newsletters" collection
 * @method Doctrine_Collection getLiens()       Returns the current record's "Liens" collection
 * @method Doctrine_Collection getAffiliates()  Returns the current record's "Affiliates" collection
 * @method category            setId()          Sets the current record's "id" value
 * @method category            setUniqueName()  Sets the current record's "unique_name" value
 * @method category            setRank()        Sets the current record's "rank" value
 * @method category            setIsActive()    Sets the current record's "is_active" value
 * @method category            setArticles()    Sets the current record's "Articles" collection
 * @method category            setNewsletters() Sets the current record's "Newsletters" collection
 * @method category            setLiens()       Sets the current record's "Liens" collection
 * @method category            setAffiliates()  Sets the current record's "Affiliates" collection
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('unique_name', 'string', 30, array(
             'type' => 'string',
             'unique' => true,
             'length' => 30,
             ));
        $this->hasColumn('rank', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'length' => 4,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('article as Articles', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('newsletter as Newsletters', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('lien as Liens', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('engine as Affiliates', array(
             'local' => 'id',
             'foreign' => 'id_category'));

        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             'rootColumnName' => 'root_id',
             ));
        $this->actAs($nestedset0);
    }
}