<?php

/**
 * BasetreeProgramme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $programme_id
 * @property integer $tree_id
 * @property tree $tree
 * @property programme $programme
 * 
 * @method integer       getProgrammeId()  Returns the current record's "programme_id" value
 * @method integer       getTreeId()       Returns the current record's "tree_id" value
 * @method tree          getTree()         Returns the current record's "tree" value
 * @method programme     getProgramme()    Returns the current record's "programme" value
 * @method treeProgramme setProgrammeId()  Sets the current record's "programme_id" value
 * @method treeProgramme setTreeId()       Sets the current record's "tree_id" value
 * @method treeProgramme setTree()         Sets the current record's "tree" value
 * @method treeProgramme setProgramme()    Sets the current record's "programme" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasetreeProgramme extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tree_programme');
        $this->hasColumn('programme_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('tree_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('tree', array(
             'local' => 'tree_id',
             'foreign' => 'id'));

        $this->hasOne('programme', array(
             'local' => 'programme_id',
             'foreign' => 'id'));
    }
}