<?php

/**
 * Baseprogramme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $organisme_id
 * @property string $title
 * @property string $accroche
 * @property clob $description
 * @property string $latitude
 * @property string $longitude
 * @property string $geoloc
 * @property boolean $is_active
 * @property integer $max_tree
 * @property organisme $organisme
 * @property Doctrine_Collection $ProgrammeTrees
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method integer             getOrganismeId()    Returns the current record's "organisme_id" value
 * @method string              getTitle()          Returns the current record's "title" value
 * @method string              getAccroche()       Returns the current record's "accroche" value
 * @method clob                getDescription()    Returns the current record's "description" value
 * @method string              getLatitude()       Returns the current record's "latitude" value
 * @method string              getLongitude()      Returns the current record's "longitude" value
 * @method string              getGeoloc()         Returns the current record's "geoloc" value
 * @method boolean             getIsActive()       Returns the current record's "is_active" value
 * @method integer             getMaxTree()        Returns the current record's "max_tree" value
 * @method organisme           getOrganisme()      Returns the current record's "organisme" value
 * @method Doctrine_Collection getProgrammeTrees() Returns the current record's "ProgrammeTrees" collection
 * @method programme           setId()             Sets the current record's "id" value
 * @method programme           setOrganismeId()    Sets the current record's "organisme_id" value
 * @method programme           setTitle()          Sets the current record's "title" value
 * @method programme           setAccroche()       Sets the current record's "accroche" value
 * @method programme           setDescription()    Sets the current record's "description" value
 * @method programme           setLatitude()       Sets the current record's "latitude" value
 * @method programme           setLongitude()      Sets the current record's "longitude" value
 * @method programme           setGeoloc()         Sets the current record's "geoloc" value
 * @method programme           setIsActive()       Sets the current record's "is_active" value
 * @method programme           setMaxTree()        Sets the current record's "max_tree" value
 * @method programme           setOrganisme()      Sets the current record's "organisme" value
 * @method programme           setProgrammeTrees() Sets the current record's "ProgrammeTrees" collection
 * 
 * @package    up2green
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseprogramme extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('programme');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('organisme_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('accroche', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));
        $this->hasColumn('latitude', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('longitude', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('geoloc', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('max_tree', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('organisme', array(
             'local' => 'organisme_id',
             'foreign' => 'id'));

        $this->hasMany('tree_programme as ProgrammeTrees', array(
             'local' => 'id',
             'foreign' => 'programme_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'accroche',
              2 => 'description',
             ),
             ));
        $sluggable1 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             'uniqueBy' => 
             array(
              0 => 'lang',
              1 => 'title',
             ),
             ));
        $i18n0->addChild($sluggable1);
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}