<?php

/**
 * BaseengineTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $engine_id
 * @property integer $tag_id
 * @property engine $engine
 * @property tag $tag
 * 
 * @method integer   getEngineId()  Returns the current record's "engine_id" value
 * @method integer   getTagId()     Returns the current record's "tag_id" value
 * @method engine    getEngine()    Returns the current record's "engine" value
 * @method tag       getTag()       Returns the current record's "tag" value
 * @method engineTag setEngineId()  Sets the current record's "engine_id" value
 * @method engineTag setTagId()     Sets the current record's "tag_id" value
 * @method engineTag setEngine()    Sets the current record's "engine" value
 * @method engineTag setTag()       Sets the current record's "tag" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseengineTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('engine_tag');
        $this->hasColumn('engine_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('tag_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('engine', array(
             'local' => 'engine_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('tag', array(
             'local' => 'tag_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}