<?php

/**
 * Basepreinscription
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $last_name
 * @property string $email_address
 * @property string $username
 * 
 * @method string         getFirstName()     Returns the current record's "first_name" value
 * @method string         getLastName()      Returns the current record's "last_name" value
 * @method string         getEmailAddress()  Returns the current record's "email_address" value
 * @method string         getUsername()      Returns the current record's "username" value
 * @method preinscription setFirstName()     Sets the current record's "first_name" value
 * @method preinscription setLastName()      Sets the current record's "last_name" value
 * @method preinscription setEmailAddress()  Sets the current record's "email_address" value
 * @method preinscription setUsername()      Sets the current record's "username" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basepreinscription extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('preinscription');
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email_address', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('username', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 128,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}