<?php

/**
 * Basecoupon
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $gen_id
 * @property string $code
 * @property boolean $is_active
 * @property timestamp $used_at
 * @property integer $used_by
 * @property couponGen $couponGen
 * @property couponUser $User
 * @property couponPartenaire $Partenaire
 * @property Doctrine_Collection $logCoupon
 * @property Doctrine_Collection $Trees
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method integer             getGenId()      Returns the current record's "gen_id" value
 * @method string              getCode()       Returns the current record's "code" value
 * @method boolean             getIsActive()   Returns the current record's "is_active" value
 * @method timestamp           getUsedAt()     Returns the current record's "used_at" value
 * @method integer             getUsedBy()     Returns the current record's "used_by" value
 * @method couponGen           getCouponGen()  Returns the current record's "couponGen" value
 * @method couponUser          getUser()       Returns the current record's "User" value
 * @method couponPartenaire    getPartenaire() Returns the current record's "Partenaire" value
 * @method Doctrine_Collection getLogCoupon()  Returns the current record's "logCoupon" collection
 * @method Doctrine_Collection getTrees()      Returns the current record's "Trees" collection
 * @method coupon              setId()         Sets the current record's "id" value
 * @method coupon              setGenId()      Sets the current record's "gen_id" value
 * @method coupon              setCode()       Sets the current record's "code" value
 * @method coupon              setIsActive()   Sets the current record's "is_active" value
 * @method coupon              setUsedAt()     Sets the current record's "used_at" value
 * @method coupon              setUsedBy()     Sets the current record's "used_by" value
 * @method coupon              setCouponGen()  Sets the current record's "couponGen" value
 * @method coupon              setUser()       Sets the current record's "User" value
 * @method coupon              setPartenaire() Sets the current record's "Partenaire" value
 * @method coupon              setLogCoupon()  Sets the current record's "logCoupon" collection
 * @method coupon              setTrees()      Sets the current record's "Trees" collection
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecoupon extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('coupon');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('gen_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('code', 'string', 128, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('used_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('used_by', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('couponGen', array(
             'local' => 'gen_id',
             'foreign' => 'id'));

        $this->hasOne('couponUser as User', array(
             'local' => 'id',
             'foreign' => 'coupon_id'));

        $this->hasOne('couponPartenaire as Partenaire', array(
             'local' => 'id',
             'foreign' => 'coupon_id'));

        $this->hasMany('logCoupon', array(
             'local' => 'id',
             'foreign' => 'coupon_id'));

        $this->hasMany('treeCoupon as Trees', array(
             'local' => 'id',
             'foreign' => 'coupon_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}