<?php

/**
 * Basepicture
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $gallery_id
 * @property string $src
 * @property gallery $Gallery
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method integer getGalleryId()  Returns the current record's "gallery_id" value
 * @method string  getSrc()        Returns the current record's "src" value
 * @method gallery getGallery()    Returns the current record's "Gallery" value
 * @method picture setId()         Sets the current record's "id" value
 * @method picture setGalleryId()  Sets the current record's "gallery_id" value
 * @method picture setSrc()        Sets the current record's "src" value
 * @method picture setGallery()    Sets the current record's "Gallery" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basepicture extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('picture');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('gallery_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('src', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('gallery as Gallery', array(
             'local' => 'gallery_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}