<?php

/**
 * BasepartenaireUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $partenaire_id
 * @property bigint $user_id
 * @property sfGuardUser $User
 * @property partenaire $partenaire
 * 
 * @method integer        getPartenaireId()  Returns the current record's "partenaire_id" value
 * @method bigint         getUserId()        Returns the current record's "user_id" value
 * @method sfGuardUser    getUser()          Returns the current record's "User" value
 * @method partenaire     getPartenaire()    Returns the current record's "partenaire" value
 * @method partenaireUser setPartenaireId()  Sets the current record's "partenaire_id" value
 * @method partenaireUser setUserId()        Sets the current record's "user_id" value
 * @method partenaireUser setUser()          Sets the current record's "User" value
 * @method partenaireUser setPartenaire()    Sets the current record's "partenaire" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasepartenaireUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('partenaire_user');
        $this->hasColumn('partenaire_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'bigint', 20, array(
             'type' => 'bigint',
             'primary' => true,
             'length' => 20,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('partenaire', array(
             'local' => 'partenaire_id',
             'foreign' => 'id'));
    }
}