<?php

/**
 * Basecontent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $layout_id
 * @property integer $zone_id
 * @property integer $module_id
 * @property layout $layout
 * @property zone $zone
 * @property module $module
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method integer getLayoutId()  Returns the current record's "layout_id" value
 * @method integer getZoneId()    Returns the current record's "zone_id" value
 * @method integer getModuleId()  Returns the current record's "module_id" value
 * @method layout  getLayout()    Returns the current record's "layout" value
 * @method zone    getZone()      Returns the current record's "zone" value
 * @method module  getModule()    Returns the current record's "module" value
 * @method content setId()        Sets the current record's "id" value
 * @method content setLayoutId()  Sets the current record's "layout_id" value
 * @method content setZoneId()    Sets the current record's "zone_id" value
 * @method content setModuleId()  Sets the current record's "module_id" value
 * @method content setLayout()    Sets the current record's "layout" value
 * @method content setZone()      Sets the current record's "zone" value
 * @method content setModule()    Sets the current record's "module" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecontent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('content');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('layout_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('zone_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('module_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('layout', array(
             'local' => 'layout_id',
             'foreign' => 'id'));

        $this->hasOne('zone', array(
             'local' => 'zone_id',
             'foreign' => 'id'));

        $this->hasOne('module', array(
             'local' => 'module_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}