<?php

/**
 * BasearticleCategorie
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $categorie_id
 * @property integer $article_id
 * @property categorie $categorie
 * @property article $article
 * 
 * @method integer          getCategorieId()  Returns the current record's "categorie_id" value
 * @method integer          getArticleId()    Returns the current record's "article_id" value
 * @method categorie        getCategorie()    Returns the current record's "categorie" value
 * @method article          getArticle()      Returns the current record's "article" value
 * @method articleCategorie setCategorieId()  Sets the current record's "categorie_id" value
 * @method articleCategorie setArticleId()    Sets the current record's "article_id" value
 * @method articleCategorie setCategorie()    Sets the current record's "categorie" value
 * @method articleCategorie setArticle()      Sets the current record's "article" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasearticleCategorie extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article_categorie');
        $this->hasColumn('categorie_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('article_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('categorie', array(
             'local' => 'categorie_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('article', array(
             'local' => 'article_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}