<?php

/**
 * BasecouponGen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property float $prix
 * @property integer $credit
 * @property Doctrine_Collection $Coupons
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method float               getPrix()    Returns the current record's "prix" value
 * @method integer             getCredit()  Returns the current record's "credit" value
 * @method Doctrine_Collection getCoupons() Returns the current record's "Coupons" collection
 * @method couponGen           setId()      Sets the current record's "id" value
 * @method couponGen           setPrix()    Sets the current record's "prix" value
 * @method couponGen           setCredit()  Sets the current record's "credit" value
 * @method couponGen           setCoupons() Sets the current record's "Coupons" collection
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasecouponGen extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('coupon_gen');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('prix', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
        $this->hasColumn('credit', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('coupon as Coupons', array(
             'local' => 'id',
             'foreign' => 'gen_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}