<?php

/**
 * Basepartenaire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $accroche
 * @property clob $description
 * @property string $url
 * @property Doctrine_Collection $partenaireUsers
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getTitle()           Returns the current record's "title" value
 * @method string              getAccroche()        Returns the current record's "accroche" value
 * @method clob                getDescription()     Returns the current record's "description" value
 * @method string              getUrl()             Returns the current record's "url" value
 * @method Doctrine_Collection getPartenaireUsers() Returns the current record's "partenaireUsers" collection
 * @method partenaire          setId()              Sets the current record's "id" value
 * @method partenaire          setTitle()           Sets the current record's "title" value
 * @method partenaire          setAccroche()        Sets the current record's "accroche" value
 * @method partenaire          setDescription()     Sets the current record's "description" value
 * @method partenaire          setUrl()             Sets the current record's "url" value
 * @method partenaire          setPartenaireUsers() Sets the current record's "partenaireUsers" collection
 * 
 * @package    up2green
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basepartenaire extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('partenaire');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('accroche', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', 65535, array(
             'type' => 'clob',
             'length' => 65535,
             ));
        $this->hasColumn('url', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('partenaireUser as partenaireUsers', array(
             'local' => 'id',
             'foreign' => 'partenaire_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}