<?php

/**
 * Basearticle_categorie
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $categorie_id
 * @property integer $article_id
 * @property categorie $categorie
 * @property article $article
 * @property Doctrine_Collection $Articles
 * @property Doctrine_Collection $Categories
 * 
 * @method integer             getCategorieId()  Returns the current record's "categorie_id" value
 * @method integer             getArticleId()    Returns the current record's "article_id" value
 * @method categorie           getCategorie()    Returns the current record's "categorie" value
 * @method article             getArticle()      Returns the current record's "article" value
 * @method Doctrine_Collection getArticles()     Returns the current record's "Articles" collection
 * @method Doctrine_Collection getCategories()   Returns the current record's "Categories" collection
 * @method article_categorie   setCategorieId()  Sets the current record's "categorie_id" value
 * @method article_categorie   setArticleId()    Sets the current record's "article_id" value
 * @method article_categorie   setCategorie()    Sets the current record's "categorie" value
 * @method article_categorie   setArticle()      Sets the current record's "article" value
 * @method article_categorie   setArticles()     Sets the current record's "Articles" collection
 * @method article_categorie   setCategories()   Sets the current record's "Categories" collection
 * 
 * @package    up2green
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basearticle_categorie extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article_categorie');
        $this->hasColumn('categorie_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('article_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('categorie', array(
             'local' => 'categorie_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('article', array(
             'local' => 'article_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('article as Articles', array(
             'refClass' => 'article_categorie',
             'local' => 'id',
             'foreign' => 'article_id'));

        $this->hasMany('categorie as Categories', array(
             'refClass' => 'article_categorie',
             'local' => 'id',
             'foreign' => 'categorie_id'));
    }
}