<?php

/**
 * Basepoint
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property decimal $latitude
 * @property decimal $longitude
 * @property decimal $altitude
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method decimal getLatitude()  Returns the current record's "latitude" value
 * @method decimal getLongitude() Returns the current record's "longitude" value
 * @method decimal getAltitude()  Returns the current record's "altitude" value
 * @method point   setId()        Sets the current record's "id" value
 * @method point   setLatitude()  Sets the current record's "latitude" value
 * @method point   setLongitude() Sets the current record's "longitude" value
 * @method point   setAltitude()  Sets the current record's "altitude" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basepoint extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('point');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('latitude', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 6,
             'notnull' => true,
             ));
        $this->hasColumn('longitude', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 6,
             'notnull' => true,
             ));
        $this->hasColumn('altitude', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 6,
             'notnull' => true,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}