<?php

/**
 * Baselien
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $src
 * @property boolean $is_active
 * @property Doctrine_Collection $lien_categorie
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getTitle()          Returns the current record's "title" value
 * @method string              getSrc()            Returns the current record's "src" value
 * @method boolean             getIsActive()       Returns the current record's "is_active" value
 * @method Doctrine_Collection getLienCategorie()  Returns the current record's "lien_categorie" collection
 * @method lien                setId()             Sets the current record's "id" value
 * @method lien                setTitle()          Sets the current record's "title" value
 * @method lien                setSrc()            Sets the current record's "src" value
 * @method lien                setIsActive()       Sets the current record's "is_active" value
 * @method lien                setLienCategorie()  Sets the current record's "lien_categorie" collection
 * 
 * @package    up2green
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baselien extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lien');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('src', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('lien_categorie', array(
             'local' => 'id',
             'foreign' => 'lien_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $sluggable1 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             'uniqueBy' => 
             array(
              0 => 'lang',
              1 => 'title',
             ),
             ));
        $i18n0->addChild($sluggable1);
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}