<?php

/**
 * BaseprogrammePolygonne
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $polygonne_id
 * @property integer $programme_id
 * @property programme $programme
 * 
 * @method integer            getPolygonneId()  Returns the current record's "polygonne_id" value
 * @method integer            getProgrammeId()  Returns the current record's "programme_id" value
 * @method programme          getProgramme()    Returns the current record's "programme" value
 * @method programmePolygonne setPolygonneId()  Sets the current record's "polygonne_id" value
 * @method programmePolygonne setProgrammeId()  Sets the current record's "programme_id" value
 * @method programmePolygonne setProgramme()    Sets the current record's "programme" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseprogrammePolygonne extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('programme_polygonne');
        $this->hasColumn('polygonne_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('programme_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('programme', array(
             'local' => 'programme_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}