<?php

/**
 * BasenewsletterCategorie
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $categorie_id
 * @property integer $newsletter_id
 * @property categorie $categorie
 * @property newsletter $newsletter
 * 
 * @method integer             getCategorieId()   Returns the current record's "categorie_id" value
 * @method integer             getNewsletterId()  Returns the current record's "newsletter_id" value
 * @method categorie           getCategorie()     Returns the current record's "categorie" value
 * @method newsletter          getNewsletter()    Returns the current record's "newsletter" value
 * @method newsletterCategorie setCategorieId()   Sets the current record's "categorie_id" value
 * @method newsletterCategorie setNewsletterId()  Sets the current record's "newsletter_id" value
 * @method newsletterCategorie setCategorie()     Sets the current record's "categorie" value
 * @method newsletterCategorie setNewsletter()    Sets the current record's "newsletter" value
 * 
 * @package    up2green
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasenewsletterCategorie extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('newsletter_categorie');
        $this->hasColumn('categorie_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('newsletter_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('categorie', array(
             'local' => 'categorie_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('newsletter', array(
             'local' => 'newsletter_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}