<?php

/**
 * article_categorie
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    up2green
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class article_categorie extends Basearticle_categorie
{
}
