<?php

/**
 * coupon
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    up2green
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class coupon extends Basecoupon {
    public function plantArbre($nb, programme $programme, $user) {
        for ($i = 0; $i < $nb; $i ++) {
            $tree = new tree();
            $tree->setProgramme($programme);
            $tree->save();

            $treeCoupon = new treeCoupon();
            $treeCoupon->setCoupon($this);
            $treeCoupon->setTree($tree);
            $treeCoupon->save();

            if ($user->getGuardUser()) {
                $treeUser = new treeUser();
                $treeUser->setTree($tree);
                $treeUser->setUser($user->getGuardUser());
                $treeUser->save();
            }
        }
    }
}