<?php

/**
 * galleryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class galleryTable extends up2gTable
{

  public function findOneBySlug($slug, Doctrine_Query $q = null)
  {
    return $this->getOne($this->addSlugQuery($slug, $q));
  }

  public function addSlugQuery($slug, Doctrine_Query $q = null)
  {
    return $this->addQuery($q)
        ->innerJoin($this->getAlias() . '.Translation t')
        ->where('t.slug = ?', $slug);
  }

  /**
   * Returns an instance of this class.
   *
   * @return object galleryTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('gallery');
  }
}