<?php

/**
 * logPubTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class logPubTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object logPubTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('logPub');
    }

    public function getForUrlAndUser($url, $idUser)
    {
        return $this->createQuery('l')
			->select('l.id')
			->where('l.user_id = ?', $idUser)
			->where('l.url = ?', $url)
			->where('l.created_at > (NOW() - INTERVAL 1 MINUTE)')
			->fetchArray();
    }
}