<?php

/**
 * mailingListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mailingListTable extends Doctrine_Table
{

  public function getDistinctEmails($forced = false, $excludes = array())
  {
    $excludes[] = '';

    $q = $this->createQuery('ml')
      ->select('DISTINCT(ml.email_address) as email')
      ->orderBy('ml.email_address')
      ->whereNotIn('ml.email_address', $excludes)
      ->andWhere('ml.email_address IS NOT NULL');

    if (!$forced) {
      $q->andWhere('ml.is_newsletter = ?', 1);
    }

    $values = $q->fetchArray();
    $return = array();

    foreach ($values as $value) {
      $return[] = $value['email'];
    }

    return $return;
  }

  /**
   * set the is_newsletter field to false for an email
   * @param string $email 
   */
  public function unsuscribe($email)
  {
    Doctrine_Query::create()
      ->update('mailingList ml')
      ->set('ml.is_newsletter', '?', 0)
      ->where('ml.email_address = ?', $email)
      ->execute();
  }

  /**
   * Returns an instance of this class.
   *
   * @return object mailingListTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('mailingList');
  }

}