<?php

/**
 * organismePointTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class organismePointTable extends pointTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object organismePointTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('organismePoint');
    }
}