<?php

/**
 * organisme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class organisme extends Baseorganisme {
	
	public function getCoordinate() {
		if($this->getLatitude() != null && $this->getLongitude() != null && $this->getAltitude() != null ) {
			return $this->getLatitude().','.$this->getLongitude().','.$this->getAltitude();
		}
		return null;
	}

}