<?php

/**
 * partenaireProgramme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class partenaireProgramme extends BasepartenaireProgramme
{

  public function __toString()
  {
    return (string) $this->getProgramme()->getTitle();
  }

}
