<?php

/**
 * partenaireLogoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class partenaireLogoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object partenaireLogoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('partenaireLogo');
    }
}