<?php

/**
 * pictureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class pictureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object pictureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('picture');
    }
}