<?php

/**
 * picture
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class picture extends Basepicture
{
  public function getPath()
  {
    return sfConfig::get('sf_upload_dir').'/gallery/'.$this->getSrc();
  }

  public function getThumbnailPath()
  {
    return sfConfig::get('sf_upload_dir').'/gallery/thumbnail/'.$this->getSrc();
  }

  /**
   * On pre update we want to remove the previous thumbnail
   *
   * @param type $event
   */
  public function preDelete($event)
  {
    // Remove the thumbnail
    @unlink($this->getThumbnailPath());
  }

  /**
   * On pre update we want to remove the previous thumbnail
   *
   * @param type $event
   */
  public function preUpdate($event)
  {
    // Remove the previous thumbnail
    @unlink($this->getThumbnailPath());
  }

  /**
   * After saving the object we want to create a thumbnail
   *
   * @param type $event
   */
  public function postSave($event)
  {
    // Create the thumbnail
    $thumbnail = new sfThumbnail(150, 150);
    $thumbnail->loadFile($this->getPath());
    $thumbnail->save($this->getThumbnailPath());
  }
}
