<?php

/**
 * pointTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class pointTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object pointTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('point');
    }
}