<?php

/**
 * point
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class point extends Basepoint
{
  public static $outputSeparator = ',';

  public function getOutput($forceAltitude = false, $inverse = false)
  {
    if ($this->isNew()) {
      return null;
    }

    if (!$inverse) {
      $coord = $this->getLongitude()
        . self::$outputSeparator
        . $this->getLatitude();
    } else {
      $coord = $this->getLatitude()
        . self::$outputSeparator
        . $this->getLongitude();
    }

    $altitude = (float) $this->getAltitude();
    if ($forceAltitude || !empty($altitude)) {
      $coord .= self::$outputSeparator . $altitude;
    }

    return $coord;
  }

}
