<?php

/**
 * polygonneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class polygonneTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object polygonneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('polygonne');
    }
}