<?php

/**
 * polygonnePointTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class polygonnePointTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object polygonnePointTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('polygonnePoint');
    }
}