<?php

/**
 * polygonne
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class polygonne extends Basepolygonne
{

  public function __toString()
  {
    return $this->getUniqueName();
  }
  /*
   * @return Point le point au centre de la zone
   */

  public function getCenter()
  {
    if ($this->isNew()) {
      return false;
    }

    $lat  = $size = $long = $alt  = 0;
    foreach ($this->getPoints() as $point) {
      $lat += $point->getLatitude();
      $long += $point->getLongitude();
      $alt += $point->getAltitude();
      $size++;
    }


    $ret = new point();
    $ret->setLatitude((float) $lat / $size);
    $ret->setLongitude((float) $long / $size);
    $ret->setAltitude((float) $alt / $size);

    return $ret;
  }

}
