<?php

/**
 * preinscriptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class preinscriptionTable extends Doctrine_Table
{

  public function getDistinctEmails($forced = false, $excludes = array())
  {
    $excludes[] = '';

    $q = $this->createQuery('p')
      ->select('DISTINCT(p.email_address) as email')
      ->orderBy('p.email_address')
      ->whereNotIn('p.email_address', $excludes)
      ->andWhere('p.email_address IS NOT NULL');

    if (!$forced) {
      $q->andWhere('p.is_newsletter = ?', 1);
    }

    $values = $q->fetchArray();
    $return = array();

    foreach ($values as $value) {
      $return[] = $value['email'];
    }

    return $return;
  }
  
  /**
   * set the is_newsletter field to false for an email
   * @param string $email 
   */
  public function unsuscribe($email)
  {
    Doctrine_Query::create()
      ->update('preinscription p')
      ->set('p.is_newsletter', '?', 0)
      ->where('p.email_address = ?', $email)
      ->execute();
  }

  /**
   * Returns an instance of this class.
   *
   * @return object preinscriptionTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('preinscription');
  }

}