<?php

/**
 * preinscriptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class preinscriptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object preinscriptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('preinscription');
    }
}