<?php

/**
 * programmePointTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class programmePointTable extends pointTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object programmePointTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('programmePoint');
    }
}