<?php

/**
 * programme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    up2green
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class programme extends Baseprogramme
{
	
	public function countTrees() {
		return sizeof($this->getTrees()); // a optimimser avec requete count
/*
		var_dump(
			Doctrine_Query::create()
				->count()
				->from('tree t')
				->innerJoin('c.Partenaire cp')
				->where('cp.partenaire_id = ?', $partenaire->getId())
				->andWhere('c.is_active = ?', false)->execute();
		)
*/
	}
	
}
