<?php

/**
 * programme
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class programme extends Baseprogramme
{
  public function countTreesVoucherPartner()
  {
    return Doctrine_Core::getTable('treeCoupon')
			->createQuery('tc')
      ->innerJoin('tc.tree t')
			->where('t.programme_id = ?', $this->getId())
			->count();
  }

  public function countTreesVoucherUser()
  {
    return Doctrine_Core::getTable('treeCoupon')
			->createQuery('tc')
      ->innerJoin('tc.tree t')
			->where('t.programme_id = ?', $this->getId())
			->count();
  }
  
  public function countTreesUser()
  {
    return Doctrine_Core::getTable('treeUser')
			->createQuery('tu')
			->innerJoin('tu.tree t')
			->where('t.programme_id = ?', $this->getId())
			->count();
  }
    
	public function countTrees() {
		return Doctrine_Core::getTable('tree')
			->createQuery('t')
			->where('t.programme_id = ?', $this->getId())
			->count();
	}
		
}
