<?php

/**
 * sessionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sessionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sessionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('session');
    }
}