<?php

/**
 * FinancialReverseDepositTransactionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FinancialReverseDepositTransactionTable extends PluginFinancialReverseDepositTransactionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object FinancialReverseDepositTransactionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FinancialReverseDepositTransaction');
    }
}