<?php

/**
 * FinancialDepositTransactionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FinancialDepositTransactionTable extends PluginFinancialDepositTransactionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object FinancialDepositTransactionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FinancialDepositTransaction');
    }
}