<?php

/**
 * FinancialReverseApprovalTransactionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FinancialReverseApprovalTransactionTable extends PluginFinancialReverseApprovalTransactionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object FinancialReverseApprovalTransactionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FinancialReverseApprovalTransaction');
    }
}