<?php

/**
 * FinancialTransactionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FinancialTransactionTable extends PluginFinancialTransactionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object FinancialTransactionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FinancialTransaction');
    }
}