<?php

/**
 * MicropaymentDebitPaymentDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MicropaymentDebitPaymentDataTable extends PluginMicropaymentDebitPaymentDataTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MicropaymentDebitPaymentDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MicropaymentDebitPaymentData');
    }
}