<?php

/**
 * PaymentListenerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaymentListenerTable extends PluginPaymentListenerTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PaymentListenerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PaymentListener');
    }
}