<?php

/**
 * PaypalPaymentDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaypalPaymentDataTable extends PluginPaypalPaymentDataTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PaypalPaymentDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PaypalPaymentData');
    }
}