<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('article_categorie', 'article_categorie_categorie_id_categorie_id', array(
             'name' => 'article_categorie_categorie_id_categorie_id',
             'local' => 'categorie_id',
             'foreign' => 'id',
             'foreignTable' => 'categorie',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('article_categorie', 'article_categorie_article_id_article_id', array(
             'name' => 'article_categorie_article_id_article_id',
             'local' => 'article_id',
             'foreign' => 'id',
             'foreignTable' => 'article',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('partenaire_user', 'partenaire_user_user_id_sf_guard_user_id', array(
             'name' => 'partenaire_user_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->createForeignKey('partenaire_user', 'partenaire_user_partenaire_id_partenaire_id', array(
             'name' => 'partenaire_user_partenaire_id_partenaire_id',
             'local' => 'partenaire_id',
             'foreign' => 'id',
             'foreignTable' => 'partenaire',
             ));
        $this->createForeignKey('profil', 'profil_user_id_sf_guard_user_id', array(
             'name' => 'profil_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('programme', 'programme_organisme_id_organisme_id', array(
             'name' => 'programme_organisme_id_organisme_id',
             'local' => 'organisme_id',
             'foreign' => 'id',
             'foreignTable' => 'organisme',
             ));
        $this->createForeignKey('tree_programme', 'tree_programme_tree_id_tree_id', array(
             'name' => 'tree_programme_tree_id_tree_id',
             'local' => 'tree_id',
             'foreign' => 'id',
             'foreignTable' => 'tree',
             ));
        $this->createForeignKey('tree_programme', 'tree_programme_programme_id_programme_id', array(
             'name' => 'tree_programme_programme_id_programme_id',
             'local' => 'programme_id',
             'foreign' => 'id',
             'foreignTable' => 'programme',
             ));
        $this->createForeignKey('user_coupon', 'user_coupon_user_id_sf_guard_user_id', array(
             'name' => 'user_coupon_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('user_coupon', 'user_coupon_coupon_id_coupon_id', array(
             'name' => 'user_coupon_coupon_id_coupon_id',
             'local' => 'coupon_id',
             'foreign' => 'id',
             'foreignTable' => 'coupon',
             ));
        $this->createForeignKey('user_tree', 'user_tree_user_id_sf_guard_user_id', array(
             'name' => 'user_tree_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('user_tree', 'user_tree_tree_id_tree_id', array(
             'name' => 'user_tree_tree_id_tree_id',
             'local' => 'tree_id',
             'foreign' => 'id',
             'foreignTable' => 'tree',
             ));
        $this->createForeignKey('article_translation', 'article_translation_id_article_id', array(
             'name' => 'article_translation_id_article_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'article',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('categorie_translation', 'categorie_translation_id_categorie_id', array(
             'name' => 'categorie_translation_id_categorie_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'categorie',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('newsletter_translation', 'newsletter_translation_id_newsletter_id', array(
             'name' => 'newsletter_translation_id_newsletter_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'newsletter',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('organisme_translation', 'organisme_translation_id_organisme_id', array(
             'name' => 'organisme_translation_id_organisme_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'organisme',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('programme_translation', 'programme_translation_id_programme_id', array(
             'name' => 'programme_translation_id_programme_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'programme',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('article_categorie', 'article_categorie_categorie_id', array(
             'fields' => 
             array(
              0 => 'categorie_id',
             ),
             ));
        $this->addIndex('article_categorie', 'article_categorie_article_id', array(
             'fields' => 
             array(
              0 => 'article_id',
             ),
             ));
        $this->addIndex('partenaire_user', 'partenaire_user_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('partenaire_user', 'partenaire_user_partenaire_id', array(
             'fields' => 
             array(
              0 => 'partenaire_id',
             ),
             ));
        $this->addIndex('profil', 'profil_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('programme', 'programme_organisme_id', array(
             'fields' => 
             array(
              0 => 'organisme_id',
             ),
             ));
        $this->addIndex('tree_programme', 'tree_programme_tree_id', array(
             'fields' => 
             array(
              0 => 'tree_id',
             ),
             ));
        $this->addIndex('tree_programme', 'tree_programme_programme_id', array(
             'fields' => 
             array(
              0 => 'programme_id',
             ),
             ));
        $this->addIndex('user_coupon', 'user_coupon_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('user_coupon', 'user_coupon_coupon_id', array(
             'fields' => 
             array(
              0 => 'coupon_id',
             ),
             ));
        $this->addIndex('user_tree', 'user_tree_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('user_tree', 'user_tree_tree_id', array(
             'fields' => 
             array(
              0 => 'tree_id',
             ),
             ));
        $this->addIndex('article_translation', 'article_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addIndex('categorie_translation', 'categorie_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addIndex('newsletter_translation', 'newsletter_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addIndex('organisme_translation', 'organisme_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addIndex('programme_translation', 'programme_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('article_categorie', 'article_categorie_categorie_id_categorie_id');
        $this->dropForeignKey('article_categorie', 'article_categorie_article_id_article_id');
        $this->dropForeignKey('partenaire_user', 'partenaire_user_user_id_sf_guard_user_id');
        $this->dropForeignKey('partenaire_user', 'partenaire_user_partenaire_id_partenaire_id');
        $this->dropForeignKey('profil', 'profil_user_id_sf_guard_user_id');
        $this->dropForeignKey('programme', 'programme_organisme_id_organisme_id');
        $this->dropForeignKey('tree_programme', 'tree_programme_tree_id_tree_id');
        $this->dropForeignKey('tree_programme', 'tree_programme_programme_id_programme_id');
        $this->dropForeignKey('user_coupon', 'user_coupon_user_id_sf_guard_user_id');
        $this->dropForeignKey('user_coupon', 'user_coupon_coupon_id_coupon_id');
        $this->dropForeignKey('user_tree', 'user_tree_user_id_sf_guard_user_id');
        $this->dropForeignKey('user_tree', 'user_tree_tree_id_tree_id');
        $this->dropForeignKey('article_translation', 'article_translation_id_article_id');
        $this->dropForeignKey('categorie_translation', 'categorie_translation_id_categorie_id');
        $this->dropForeignKey('newsletter_translation', 'newsletter_translation_id_newsletter_id');
        $this->dropForeignKey('organisme_translation', 'organisme_translation_id_organisme_id');
        $this->dropForeignKey('programme_translation', 'programme_translation_id_programme_id');
        $this->removeIndex('article_categorie', 'article_categorie_categorie_id', array(
             'fields' => 
             array(
              0 => 'categorie_id',
             ),
             ));
        $this->removeIndex('article_categorie', 'article_categorie_article_id', array(
             'fields' => 
             array(
              0 => 'article_id',
             ),
             ));
        $this->removeIndex('partenaire_user', 'partenaire_user_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('partenaire_user', 'partenaire_user_partenaire_id', array(
             'fields' => 
             array(
              0 => 'partenaire_id',
             ),
             ));
        $this->removeIndex('profil', 'profil_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('programme', 'programme_organisme_id', array(
             'fields' => 
             array(
              0 => 'organisme_id',
             ),
             ));
        $this->removeIndex('tree_programme', 'tree_programme_tree_id', array(
             'fields' => 
             array(
              0 => 'tree_id',
             ),
             ));
        $this->removeIndex('tree_programme', 'tree_programme_programme_id', array(
             'fields' => 
             array(
              0 => 'programme_id',
             ),
             ));
        $this->removeIndex('user_coupon', 'user_coupon_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('user_coupon', 'user_coupon_coupon_id', array(
             'fields' => 
             array(
              0 => 'coupon_id',
             ),
             ));
        $this->removeIndex('user_tree', 'user_tree_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('user_tree', 'user_tree_tree_id', array(
             'fields' => 
             array(
              0 => 'tree_id',
             ),
             ));
        $this->removeIndex('article_translation', 'article_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->removeIndex('categorie_translation', 'categorie_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->removeIndex('newsletter_translation', 'newsletter_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->removeIndex('organisme_translation', 'organisme_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->removeIndex('programme_translation', 'programme_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}