<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('article', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'logo' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('article_categorie', array(
             'categorie_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             'article_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'categorie_id',
              1 => 'article_id',
             ),
             ));
        $this->createTable('categorie', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'parent_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('coupon', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'code' => 
             array(
              'type' => 'string',
              'unique' => '1',
              'notnull' => '1',
              'length' => '128',
             ),
             'credit' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'default' => '1',
              'length' => '4',
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'default' => '1',
              'length' => '25',
             ),
             'is_used' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'used_at' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'used_by' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('newsletter', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'reply_to' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'default' => 'noreply@up2green.com',
              'length' => '128',
             ),
             'email_from' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'default' => 'newsletter@up2green.com',
              'length' => '128',
             ),
             'is_forced' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'default' => '0',
              'length' => '1',
             ),
             'sent_at' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('organisme', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '128',
             ),
             'url' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'logo' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('partenaire', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '45',
             ),
             'accroche' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'length' => '65535',
             ),
             'url' => 
             array(
              'type' => 'string',
              'length' => '150',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('partenaire_user', array(
             'partenaire_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'partenaire_id',
              1 => 'user_id',
             ),
             ));
        $this->createTable('profil', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'unique' => '1',
              'length' => '4',
             ),
             'credit' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'default' => '0',
              'length' => '4',
             ),
             'is_newsletter' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'default' => '0',
              'length' => '1',
             ),
             'culture' => 
             array(
              'type' => 'string',
              'default' => 'fr_FR',
              'length' => '7',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('programme', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'organisme_id' => 
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'latitude' => 
             array(
              'type' => 'string',
              'length' => '45',
             ),
             'longitude' => 
             array(
              'type' => 'string',
              'length' => '45',
             ),
             'geoloc' => 
             array(
              'type' => 'string',
              'length' => '100',
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'default' => '1',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('tree', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'cost' => 
             array(
              'type' => 'string',
              'length' => '45',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('tree_programme', array(
             'programme_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             'tree_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'programme_id',
              1 => 'tree_id',
             ),
             ));
        $this->createTable('user_coupon', array(
             'user_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             'coupon_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'user_id',
              1 => 'coupon_id',
             ),
             ));
        $this->createTable('user_tree', array(
             'user_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             'tree_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'user_id',
              1 => 'tree_id',
             ),
             ));
        $this->createTable('article_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'accroche' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'length' => '65535',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             ), array(
             'indexes' => 
             array(
              'article_translation_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
               1 => 'lang',
               2 => 'title',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             ));
        $this->createTable('categorie_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '128',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             ), array(
             'indexes' => 
             array(
              'categorie_translation_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
               1 => 'lang',
               2 => 'name',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             ));
        $this->createTable('newsletter_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'content' => 
             array(
              'type' => 'clob',
              'length' => '65535',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             ), array(
             'indexes' => 
             array(
              'newsletter_translation_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
               1 => 'lang',
               2 => 'title',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             ));
        $this->createTable('organisme_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '128',
             ),
             'accroche' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'length' => '65535',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             ), array(
             'indexes' => 
             array(
              'organisme_translation_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
               1 => 'lang',
               2 => 'title',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             ));
        $this->createTable('programme_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'accroche' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'length' => '65535',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             ), array(
             'indexes' => 
             array(
              'programme_translation_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
               1 => 'lang',
               2 => 'title',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('article');
        $this->dropTable('article_categorie');
        $this->dropTable('categorie');
        $this->dropTable('coupon');
        $this->dropTable('newsletter');
        $this->dropTable('organisme');
        $this->dropTable('partenaire');
        $this->dropTable('partenaire_user');
        $this->dropTable('profil');
        $this->dropTable('programme');
        $this->dropTable('tree');
        $this->dropTable('tree_programme');
        $this->dropTable('user_coupon');
        $this->dropTable('user_tree');
        $this->dropTable('article_translation');
        $this->dropTable('categorie_translation');
        $this->dropTable('newsletter_translation');
        $this->dropTable('organisme_translation');
        $this->dropTable('programme_translation');
    }
}