<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('categorie', 'lft', 'integer', '4', array(
             ));
        $this->addColumn('categorie', 'rgt', 'integer', '4', array(
             ));
        $this->addColumn('categorie', 'level', 'integer', '2', array(
             ));
        $this->changeColumn('categorie', 'parent_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('categorie', 'lft');
        $this->removeColumn('categorie', 'rgt');
        $this->removeColumn('categorie', 'level');
    }
}