<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version47 extends Doctrine_Migration_Base
{
    public function up()
    {
			$this->dropTable('polygonne_point');
			$this->createTable('polygonne_point', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'latitude' => 
             array(
              'type' => 'decimal',
              'scale' => '6',
              'notnull' => '1',
              'length' => '18',
             ),
             'longitude' => 
             array(
              'type' => 'decimal',
              'scale' => '6',
              'notnull' => '1',
              'length' => '18',
             ),
             'altitude' => 
             array(
              'type' => 'decimal',
              'scale' => '6',
              'notnull' => '1',
              'length' => '18',
             ),
             'polygonne_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
              1 => 'polygonne_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('polygonne_point');
				$this->createTable('polygonne_point', array(
             'polygonne_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             'latitude' => 
             array(
              'type' => 'decimal',
              'scale' => '6',
              'notnull' => '1',
              'length' => '18',
             ),
             'longitude' => 
             array(
              'type' => 'decimal',
              'scale' => '6',
              'notnull' => '1',
              'length' => '18',
             ),
             'altitude' => 
             array(
              'type' => 'decimal',
              'scale' => '6',
              'notnull' => '1',
              'length' => '18',
             ),
             ), array(
             'primary' => array(
              0 => 'polygonne_id',
             ),
             ));
    }
}