<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version46 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('organisme', 'organisme_point_id_point_id');
        $this->dropForeignKey('polygonne_point', 'polygonne_point_point_id_point_id');
        $this->dropForeignKey('programme', 'programme_point_id_point_id');
        $this->createForeignKey('organisme_point', 'organisme_point_organisme_id_organisme_id', array(
             'name' => 'organisme_point_organisme_id_organisme_id',
             'local' => 'organisme_id',
             'foreign' => 'id',
             'foreignTable' => 'organisme',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('programme_point', 'programme_point_programme_id_programme_id', array(
             'name' => 'programme_point_programme_id_programme_id',
             'local' => 'programme_id',
             'foreign' => 'id',
             'foreignTable' => 'programme',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('organisme_point', 'organisme_point_organisme_id', array(
             'fields' => 
             array(
              0 => 'organisme_id',
             ),
             ));
        $this->addIndex('programme_point', 'programme_point_programme_id', array(
             'fields' => 
             array(
              0 => 'programme_id',
             ),
             ));
				$this->removeColumn('organisme', 'point_id');
        $this->removeColumn('programme', 'point_id');
    }

    public function down()
    {
        $this->createForeignKey('organisme', 'organisme_point_id_point_id', array(
             'name' => 'organisme_point_id_point_id',
             'local' => 'point_id',
             'foreign' => 'id',
             'foreignTable' => 'point',
             ));
        $this->createForeignKey('polygonne_point', 'polygonne_point_point_id_point_id', array(
             'name' => 'polygonne_point_point_id_point_id',
             'local' => 'point_id',
             'foreign' => 'id',
             'foreignTable' => 'point',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('programme', 'programme_point_id_point_id', array(
             'name' => 'programme_point_id_point_id',
             'local' => 'point_id',
             'foreign' => 'id',
             'foreignTable' => 'point',
             ));
        $this->dropForeignKey('organisme_point', 'organisme_point_organisme_id_organisme_id');
        $this->dropForeignKey('programme_point', 'programme_point_programme_id_programme_id');
        $this->removeIndex('organisme_point', 'organisme_point_organisme_id', array(
             'fields' => 
             array(
              0 => 'organisme_id',
             ),
             ));
        $this->removeIndex('programme_point', 'programme_point_programme_id', array(
             'fields' => 
             array(
              0 => 'programme_id',
             ),
             ));
				$this->addColumn('organisme', 'point_id', 'integer', '4', array(
             ));
        $this->addColumn('programme', 'point_id', 'integer', '4', array(
             ));
    }
}