<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addnewsletter extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('newsletter', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'category_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
             ),
             'reply_to' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'default' => 'noreply@up2green.com',
              'length' => 128,
             ),
             'email_from' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'default' => 'newsletter@up2green.com',
              'length' => 128,
             ),
             'is_forced' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'length' => 25,
             ),
             'sent_at' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('newsletter');
    }
}