<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addprofil extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('profil', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'user_id' => 
             array(
              'type' => 'bigint',
              'notnull' => true,
              'unique' => true,
              'length' => 20,
             ),
             'credit' => 
             array(
              'type' => 'float',
              'notnull' => true,
              'default' => 0,
              'length' => 18,
              'scale' => '4',
             ),
             'is_newsletter' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'default' => 0,
              'length' => 1,
             ),
             'culture' => 
             array(
              'type' => 'string',
              'default' => 'fr_FR',
              'length' => 7,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('profil');
    }
}