<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version43 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('point', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'latitude' => 
             array(
              'type' => 'decimal',
              'scale' => '6',
              'notnull' => '1',
              'length' => '18',
             ),
             'longitude' => 
             array(
              'type' => 'decimal',
              'scale' => '6',
              'notnull' => '1',
              'length' => '18',
             ),
             'altitude' => 
             array(
              'type' => 'decimal',
              'scale' => '6',
              'notnull' => '1',
              'length' => '18',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('polygonne', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'unique_name' => 
             array(
              'type' => 'string',
              'unique' => '1',
              'notnull' => '1',
              'length' => '30',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('polygonne_point', array(
             'polygonne_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             'point_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'polygonne_id',
              1 => 'point_id',
             ),
             ));
        $this->createTable('programme_polygonne', array(
             'polygonne_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             'programme_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'polygonne_id',
              1 => 'programme_id',
             ),
             ));
        $this->removeColumn('programme', 'latitude');
        $this->removeColumn('programme', 'longitude');
        $this->addColumn('organisme', 'point_id', 'integer', '4', array(
             ));
        $this->addColumn('organisme', 'is_active', 'boolean', '25', array(
             'default' => '1',
             ));
        $this->addColumn('programme', 'point_id', 'integer', '4', array(
             ));
    }

    public function down()
    {
        $this->dropTable('point');
        $this->dropTable('polygonne');
        $this->dropTable('polygonne_point');
        $this->dropTable('programme_polygonne');
        $this->addColumn('programme', 'latitude', 'decimal', '18', array(
             'scale' => '6',
             ));
        $this->addColumn('programme', 'longitude', 'decimal', '18', array(
             'scale' => '6',
             ));
        $this->removeColumn('organisme', 'point_id');
        $this->removeColumn('organisme', 'is_active');
        $this->removeColumn('programme', 'point_id');
    }
}