<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version44 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('organisme', 'organisme_point_id_point_id', array(
             'name' => 'organisme_point_id_point_id',
             'local' => 'point_id',
             'foreign' => 'id',
             'foreignTable' => 'point',
             ));
        $this->createForeignKey('programme', 'programme_point_id_point_id', array(
             'name' => 'programme_point_id_point_id',
             'local' => 'point_id',
             'foreign' => 'id',
             'foreignTable' => 'point',
             ));
        $this->addIndex('organisme', 'organisme_point_id', array(
             'fields' => 
             array(
              0 => 'point_id',
             ),
             ));
        $this->addIndex('programme', 'programme_point_id', array(
             'fields' => 
             array(
              0 => 'point_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('organisme', 'organisme_point_id_point_id');
        $this->dropForeignKey('programme', 'programme_point_id_point_id');
        $this->removeIndex('organisme', 'organisme_point_id', array(
             'fields' => 
             array(
              0 => 'point_id',
             ),
             ));
        $this->removeIndex('programme', 'programme_point_id', array(
             'fields' => 
             array(
              0 => 'point_id',
             ),
             ));
    }
}