<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addlogpub extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('log_pub', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'user_id' => 
             array(
              'type' => 'bigint',
              'length' => 20,
             ),
             'ip' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 15,
             ),
             'url' => 
             array(
              'type' => 'clob',
              'notnull' => true,
              'length' => NULL,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('log_pub');
    }
}