<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addlientranslation extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('lien_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'primary' => true,
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'lang' => 
             array(
              'fixed' => true,
              'primary' => true,
              'type' => 'string',
              'length' => 2,
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
              'lien_translation_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
               1 => 'lang',
               2 => 'title',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('lien_translation');
    }
}