<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addpartenaire extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('partenaire', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'user_id' => 
             array(
              'type' => 'bigint',
              'notnull' => true,
              'unique' => true,
              'length' => 20,
             ),
             'logo' => 
             array(
              'type' => 'string',
              'length' => 128,
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => 45,
             ),
             'accroche' => 
             array(
              'type' => 'string',
              'length' => 1000,
             ),
             'description' => 
             array(
              'type' => 'clob',
              'length' => 65535,
             ),
             'url' => 
             array(
              'type' => 'string',
              'length' => 150,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('partenaire');
    }
}