<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('article', 'article_category_id_category_id', array(
             'name' => 'article_category_id_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'category',
             ));
        $this->createForeignKey('content', 'content_layout_id_layout_id', array(
             'name' => 'content_layout_id_layout_id',
             'local' => 'layout_id',
             'foreign' => 'id',
             'foreignTable' => 'layout',
             ));
        $this->createForeignKey('content', 'content_zone_id_zone_id', array(
             'name' => 'content_zone_id_zone_id',
             'local' => 'zone_id',
             'foreign' => 'id',
             'foreignTable' => 'zone',
             ));
        $this->createForeignKey('content', 'content_module_id_module_id', array(
             'name' => 'content_module_id_module_id',
             'local' => 'module_id',
             'foreign' => 'id',
             'foreignTable' => 'module',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('coupon', 'coupon_gen_id_coupon_gen_id', array(
             'name' => 'coupon_gen_id_coupon_gen_id',
             'local' => 'gen_id',
             'foreign' => 'id',
             'foreignTable' => 'coupon_gen',
             ));
        $this->createForeignKey('coupon_partenaire', 'coupon_partenaire_partenaire_id_partenaire_id', array(
             'name' => 'coupon_partenaire_partenaire_id_partenaire_id',
             'local' => 'partenaire_id',
             'foreign' => 'id',
             'foreignTable' => 'partenaire',
             ));
        $this->createForeignKey('coupon_partenaire', 'coupon_partenaire_coupon_id_coupon_id', array(
             'name' => 'coupon_partenaire_coupon_id_coupon_id',
             'local' => 'coupon_id',
             'foreign' => 'id',
             'foreignTable' => 'coupon',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('coupon_user', 'coupon_user_user_id_sf_guard_user_id', array(
             'name' => 'coupon_user_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->createForeignKey('coupon_user', 'coupon_user_coupon_id_coupon_id', array(
             'name' => 'coupon_user_coupon_id_coupon_id',
             'local' => 'coupon_id',
             'foreign' => 'id',
             'foreignTable' => 'coupon',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('engine', 'engine_id_devise_devise_id', array(
             'name' => 'engine_id_devise_devise_id',
             'local' => 'id_devise',
             'foreign' => 'id',
             'foreignTable' => 'devise',
             ));
        $this->createForeignKey('engine', 'engine_id_plateforme_affiliate_plateforme_id', array(
             'name' => 'engine_id_plateforme_affiliate_plateforme_id',
             'local' => 'id_plateforme',
             'foreign' => 'id',
             'foreignTable' => 'affiliate_plateforme',
             ));
        $this->createForeignKey('engine', 'engine_id_category_category_id', array(
             'name' => 'engine_id_category_category_id',
             'local' => 'id_category',
             'foreign' => 'id',
             'foreignTable' => 'category',
             ));
        $this->createForeignKey('engine_tag', 'engine_tag_engine_id_engine_id', array(
             'name' => 'engine_tag_engine_id_engine_id',
             'local' => 'engine_id',
             'foreign' => 'id',
             'foreignTable' => 'engine',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('engine_tag', 'engine_tag_tag_id_tag_id', array(
             'name' => 'engine_tag_tag_id_tag_id',
             'local' => 'tag_id',
             'foreign' => 'id',
             'foreignTable' => 'tag',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('lien', 'lien_category_id_category_id', array(
             'name' => 'lien_category_id_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'category',
             ));
        $this->createForeignKey('log_coupon', 'log_coupon_coupon_id_coupon_id', array(
             'name' => 'log_coupon_coupon_id_coupon_id',
             'local' => 'coupon_id',
             'foreign' => 'id',
             'foreignTable' => 'coupon',
             ));
        $this->createForeignKey('log_pub', 'log_pub_user_id_sf_guard_user_id', array(
             'name' => 'log_pub_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->createForeignKey('newsletter', 'newsletter_category_id_category_id', array(
             'name' => 'newsletter_category_id_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'category',
             ));
        $this->createForeignKey('partenaire', 'partenaire_user_id_sf_guard_user_id', array(
             'name' => 'partenaire_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('partenaire_programme', 'partenaire_programme_partenaire_id_partenaire_id', array(
             'name' => 'partenaire_programme_partenaire_id_partenaire_id',
             'local' => 'partenaire_id',
             'foreign' => 'id',
             'foreignTable' => 'partenaire',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('partenaire_programme', 'partenaire_programme_programme_id_programme_id', array(
             'name' => 'partenaire_programme_programme_id_programme_id',
             'local' => 'programme_id',
             'foreign' => 'id',
             'foreignTable' => 'programme',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('profil', 'profil_user_id_sf_guard_user_id', array(
             'name' => 'profil_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('programme', 'programme_organisme_id_organisme_id', array(
             'name' => 'programme_organisme_id_organisme_id',
             'local' => 'organisme_id',
             'foreign' => 'id',
             'foreignTable' => 'organisme',
             ));
        $this->createForeignKey('sf_guard_forgot_password', 'sf_guard_forgot_password_user_id_sf_guard_user_id', array(
             'name' => 'sf_guard_forgot_password_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_group_permission', 'sf_guard_group_permission_group_id_sf_guard_group_id', array(
             'name' => 'sf_guard_group_permission_group_id_sf_guard_group_id',
             'local' => 'group_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_group',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_group_permission', 'sf_guard_group_permission_permission_id_sf_guard_permission_id', array(
             'name' => 'sf_guard_group_permission_permission_id_sf_guard_permission_id',
             'local' => 'permission_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_permission',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_remember_key', 'sf_guard_remember_key_user_id_sf_guard_user_id', array(
             'name' => 'sf_guard_remember_key_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_user_group', 'sf_guard_user_group_user_id_sf_guard_user_id', array(
             'name' => 'sf_guard_user_group_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_user_group', 'sf_guard_user_group_group_id_sf_guard_group_id', array(
             'name' => 'sf_guard_user_group_group_id_sf_guard_group_id',
             'local' => 'group_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_group',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_user_permission', 'sf_guard_user_permission_user_id_sf_guard_user_id', array(
             'name' => 'sf_guard_user_permission_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('sf_guard_user_permission', 'sf_guard_user_permission_permission_id_sf_guard_permission_id', array(
             'name' => 'sf_guard_user_permission_permission_id_sf_guard_permission_id',
             'local' => 'permission_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_permission',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('tree', 'tree_programme_id_programme_id', array(
             'name' => 'tree_programme_id_programme_id',
             'local' => 'programme_id',
             'foreign' => 'id',
             'foreignTable' => 'programme',
             ));
        $this->createForeignKey('tree_coupon', 'tree_coupon_tree_id_tree_id', array(
             'name' => 'tree_coupon_tree_id_tree_id',
             'local' => 'tree_id',
             'foreign' => 'id',
             'foreignTable' => 'tree',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('tree_coupon', 'tree_coupon_coupon_id_coupon_id', array(
             'name' => 'tree_coupon_coupon_id_coupon_id',
             'local' => 'coupon_id',
             'foreign' => 'id',
             'foreignTable' => 'coupon',
             ));
        $this->createForeignKey('tree_user', 'tree_user_tree_id_tree_id', array(
             'name' => 'tree_user_tree_id_tree_id',
             'local' => 'tree_id',
             'foreign' => 'id',
             'foreignTable' => 'tree',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('tree_user', 'tree_user_user_id_sf_guard_user_id', array(
             'name' => 'tree_user_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->createForeignKey('article_translation', 'article_translation_id_article_id', array(
             'name' => 'article_translation_id_article_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'article',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('lien_translation', 'lien_translation_id_lien_id', array(
             'name' => 'lien_translation_id_lien_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'lien',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('newsletter_translation', 'newsletter_translation_id_newsletter_id', array(
             'name' => 'newsletter_translation_id_newsletter_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'newsletter',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('organisme_translation', 'organisme_translation_id_organisme_id', array(
             'name' => 'organisme_translation_id_organisme_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'organisme',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('programme_translation', 'programme_translation_id_programme_id', array(
             'name' => 'programme_translation_id_programme_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'programme',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('article', 'article_category_id_category_id');
        $this->dropForeignKey('content', 'content_layout_id_layout_id');
        $this->dropForeignKey('content', 'content_zone_id_zone_id');
        $this->dropForeignKey('content', 'content_module_id_module_id');
        $this->dropForeignKey('coupon', 'coupon_gen_id_coupon_gen_id');
        $this->dropForeignKey('coupon_partenaire', 'coupon_partenaire_partenaire_id_partenaire_id');
        $this->dropForeignKey('coupon_partenaire', 'coupon_partenaire_coupon_id_coupon_id');
        $this->dropForeignKey('coupon_user', 'coupon_user_user_id_sf_guard_user_id');
        $this->dropForeignKey('coupon_user', 'coupon_user_coupon_id_coupon_id');
        $this->dropForeignKey('engine', 'engine_id_devise_devise_id');
        $this->dropForeignKey('engine', 'engine_id_plateforme_affiliate_plateforme_id');
        $this->dropForeignKey('engine', 'engine_id_category_category_id');
        $this->dropForeignKey('engine_tag', 'engine_tag_engine_id_engine_id');
        $this->dropForeignKey('engine_tag', 'engine_tag_tag_id_tag_id');
        $this->dropForeignKey('lien', 'lien_category_id_category_id');
        $this->dropForeignKey('log_coupon', 'log_coupon_coupon_id_coupon_id');
        $this->dropForeignKey('log_pub', 'log_pub_user_id_sf_guard_user_id');
        $this->dropForeignKey('newsletter', 'newsletter_category_id_category_id');
        $this->dropForeignKey('partenaire', 'partenaire_user_id_sf_guard_user_id');
        $this->dropForeignKey('partenaire_programme', 'partenaire_programme_partenaire_id_partenaire_id');
        $this->dropForeignKey('partenaire_programme', 'partenaire_programme_programme_id_programme_id');
        $this->dropForeignKey('profil', 'profil_user_id_sf_guard_user_id');
        $this->dropForeignKey('programme', 'programme_organisme_id_organisme_id');
        $this->dropForeignKey('sf_guard_forgot_password', 'sf_guard_forgot_password_user_id_sf_guard_user_id');
        $this->dropForeignKey('sf_guard_group_permission', 'sf_guard_group_permission_group_id_sf_guard_group_id');
        $this->dropForeignKey('sf_guard_group_permission', 'sf_guard_group_permission_permission_id_sf_guard_permission_id');
        $this->dropForeignKey('sf_guard_remember_key', 'sf_guard_remember_key_user_id_sf_guard_user_id');
        $this->dropForeignKey('sf_guard_user_group', 'sf_guard_user_group_user_id_sf_guard_user_id');
        $this->dropForeignKey('sf_guard_user_group', 'sf_guard_user_group_group_id_sf_guard_group_id');
        $this->dropForeignKey('sf_guard_user_permission', 'sf_guard_user_permission_user_id_sf_guard_user_id');
        $this->dropForeignKey('sf_guard_user_permission', 'sf_guard_user_permission_permission_id_sf_guard_permission_id');
        $this->dropForeignKey('tree', 'tree_programme_id_programme_id');
        $this->dropForeignKey('tree_coupon', 'tree_coupon_tree_id_tree_id');
        $this->dropForeignKey('tree_coupon', 'tree_coupon_coupon_id_coupon_id');
        $this->dropForeignKey('tree_user', 'tree_user_tree_id_tree_id');
        $this->dropForeignKey('tree_user', 'tree_user_user_id_sf_guard_user_id');
        $this->dropForeignKey('article_translation', 'article_translation_id_article_id');
        $this->dropForeignKey('lien_translation', 'lien_translation_id_lien_id');
        $this->dropForeignKey('newsletter_translation', 'newsletter_translation_id_newsletter_id');
        $this->dropForeignKey('organisme_translation', 'organisme_translation_id_organisme_id');
        $this->dropForeignKey('programme_translation', 'programme_translation_id_programme_id');
    }
}