<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addmodule extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('module', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'content_id' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 128,
             ),
             'content_type' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'category',
              1 => 'lien',
              2 => 'article',
              3 => 'newsletter',
              4 => 'programme',
              5 => 'organisme',
              6 => 'gmap',
              7 => 'recherche',
              8 => 'user',
              9 => 'sfGuardAuth',
              ),
              'length' => NULL,
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'length' => 25,
             ),
             'action' => 
             array(
              'type' => 'string',
              'length' => 128,
             ),
             'user_access' => 
             array(
              'type' => 'string',
              'length' => 128,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('module');
    }
}