<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version43 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('programme', 'latitude');
        $this->removeColumn('programme', 'longitude');
        $this->addColumn('organisme', 'point_id', 'integer', '4', array(
             ));
        $this->addColumn('organisme', 'is_active', 'boolean', '25', array(
             'default' => '1',
             ));
        $this->addColumn('programme', 'point_id', 'integer', '4', array(
             ));
    }

    public function down()
    {
        $this->addColumn('programme', 'latitude', 'decimal', '18', array(
             'scale' => '6',
             ));
        $this->addColumn('programme', 'longitude', 'decimal', '18', array(
             'scale' => '6',
             ));
        $this->removeColumn('organisme', 'point_id');
        $this->removeColumn('organisme', 'is_active');
        $this->removeColumn('programme', 'point_id');
    }
}