<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addlayout extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('layout', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 128,
             ),
             'unique_name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'unique' => true,
              'length' => 128,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('layout');
    }
}