<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version45 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('organisme_point', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'latitude' => 
             array(
              'type' => 'decimal',
              'scale' => '6',
              'notnull' => '1',
              'length' => '18',
             ),
             'longitude' => 
             array(
              'type' => 'decimal',
              'scale' => '6',
              'notnull' => '1',
              'length' => '18',
             ),
             'altitude' => 
             array(
              'type' => 'decimal',
              'scale' => '6',
              'notnull' => '1',
              'length' => '18',
             ),
             'organisme_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
              1 => 'organisme_id',
             ),
             ));
        $this->createTable('programme_point', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'latitude' => 
             array(
              'type' => 'decimal',
              'scale' => '6',
              'notnull' => '1',
              'length' => '18',
             ),
             'longitude' => 
             array(
              'type' => 'decimal',
              'scale' => '6',
              'notnull' => '1',
              'length' => '18',
             ),
             'altitude' => 
             array(
              'type' => 'decimal',
              'scale' => '6',
              'notnull' => '1',
              'length' => '18',
             ),
             'programme_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '4',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
              1 => 'programme_id',
             ),
             ));
        
    }

    public function down()
    {
        $this->dropTable('organisme_point');
        $this->dropTable('programme_point');
    }
}