<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addsession extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('session', array(
             'sess_id' => 
             array(
              'type' => 'string',
              'length' => 64,
              'primary' => true,
             ),
             'sess_data' => 
             array(
              'type' => 'clob',
              'length' => 65532,
              'notnull' => true,
             ),
             'sess_time' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 4,
             ),
             'is_authenticated' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'length' => 25,
             ),
             'last_request_time' => 
             array(
              'type' => 'integer',
              'length' => 4,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
             ),
             'app' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'module' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'action' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'is_ajax' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'length' => 25,
             ),
             'ip' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'culture' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'user_agent' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'sess_id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('session');
    }
}