<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adddevise extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('devise', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'unique_name' => 
             array(
              'type' => 'string',
              'unique' => true,
              'length' => 30,
             ),
             'conversion' => 
             array(
              'type' => 'double',
              'notnull' => true,
              'length' => 18,
              'scale' => '10',
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('devise');
    }
}