<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addpartenaireprogramme extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('partenaire_programme', array(
             'partenaire_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
             ),
             'programme_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'partenaire_id',
              1 => 'programme_id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('partenaire_programme');
    }
}