<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addcoupon extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('coupon', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'gen_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 4,
             ),
             'code' => 
             array(
              'type' => 'string',
              'unique' => true,
              'notnull' => true,
              'length' => 128,
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'default' => 1,
              'length' => 25,
             ),
             'used_at' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'used_by' => 
             array(
              'type' => 'integer',
              'length' => 4,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('coupon');
    }
}