<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addtreecoupon extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('tree_coupon', array(
             'tree_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
             ),
             'coupon_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'tree_id',
              1 => 'coupon_id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('tree_coupon');
    }
}