<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version51 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('coupon_gen', 'is_purchasable', 'boolean', '25', array(
             'default' => '1',
             ));
        $this->addColumn('coupon_gen', 'is_partenaire_only', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('coupon_gen', 'is_purchasable');
        $this->removeColumn('coupon_gen', 'is_partenaire_only');
    }
}