<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version50 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('financial_transactions', 'financial_transactions_payment_id_payments_id', array(
             'name' => 'financial_transactions_payment_id_payments_id',
             'local' => 'payment_id',
             'foreign' => 'id',
             'foreignTable' => 'payments',
             ));
        $this->createForeignKey('payment_listeners', 'payment_listeners_payment_id_payments_id', array(
             'name' => 'payment_listeners_payment_id_payments_id',
             'local' => 'payment_id',
             'foreign' => 'id',
             'foreignTable' => 'payments',
             ));
        $this->createForeignKey('currency_version', 'currency_version_id_currencies_id', array(
             'name' => 'currency_version_id_currencies_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'currencies',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('financial_transactions', 'financial_transactions_payment_id', array(
             'fields' => 
             array(
              0 => 'payment_id',
             ),
             ));
        $this->addIndex('payment_data', 'payment_data_method_class_name', array(
             'fields' => 
             array(
              0 => 'method_class_name',
             ),
             ));
        $this->addIndex('payment_listeners', 'payment_listeners_payment_id', array(
             'fields' => 
             array(
              0 => 'payment_id',
             ),
             ));
        $this->addIndex('currency_version', 'currency_version_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('financial_transactions', 'financial_transactions_payment_id_payments_id');
        $this->dropForeignKey('payment_listeners', 'payment_listeners_payment_id_payments_id');
        $this->dropForeignKey('currency_version', 'currency_version_id_currencies_id');
        $this->removeIndex('financial_transactions', 'financial_transactions_payment_id', array(
             'fields' => 
             array(
              0 => 'payment_id',
             ),
             ));
        $this->removeIndex('payment_data', 'payment_data_method_class_name', array(
             'fields' => 
             array(
              0 => 'method_class_name',
             ),
             ));
        $this->removeIndex('payment_listeners', 'payment_listeners_payment_id', array(
             'fields' => 
             array(
              0 => 'payment_id',
             ),
             ));
        $this->removeIndex('currency_version', 'currency_version_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}