<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version55 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('filleul', 'filleul_user_id_sf_guard_user_id', array(
             'name' => 'filleul_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('filleul', 'filleul_filleul_id_sf_guard_user_id', array(
             'name' => 'filleul_filleul_id_sf_guard_user_id',
             'local' => 'filleul_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->addIndex('filleul', 'filleul_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('filleul', 'filleul_filleul_id', array(
             'fields' => 
             array(
              0 => 'filleul_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('filleul', 'filleul_user_id_sf_guard_user_id');
        $this->dropForeignKey('filleul', 'filleul_filleul_id_sf_guard_user_id');
        $this->removeIndex('filleul', 'filleul_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('filleul', 'filleul_filleul_id', array(
             'fields' => 
             array(
              0 => 'filleul_id',
             ),
             ));
    }
}