<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version53 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('engine', 'engine_id_devise_devise_id');
        $this->createForeignKey('engine', 'engine_currency_id_currencies_id', array(
             'name' => 'engine_currency_id_currencies_id',
             'local' => 'currency_id',
             'foreign' => 'id',
             'foreignTable' => 'currencies',
             ));
        $this->addIndex('engine', 'engine_currency_id', array(
             'fields' => 
             array(
              0 => 'currency_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('engine', 'engine_id_devise_devise_id', array(
             'name' => 'engine_id_devise_devise_id',
             'local' => 'id_devise',
             'foreign' => 'id',
             'foreignTable' => 'devise',
             ));
        $this->dropForeignKey('engine', 'engine_currency_id_currencies_id');
        $this->removeIndex('engine', 'engine_currency_id', array(
             'fields' => 
             array(
              0 => 'currency_id',
             ),
             ));
    }
}