<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version57 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('programme', 'add_tree', 'integer', '4', array(
             'notnull' => '1',
             'default' => '0',
             ));
    }

    public function down()
    {

    }
}