<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version59 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('partenaire', 'page', 'clob', '65535', array(
             ));
        $this->addColumn('partenaire', 'attestation', 'string', '128', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('partenaire', 'page');
        $this->removeColumn('partenaire', 'attestation');
    }
}