<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version63 extends Doctrine_Migration_Base
{
    public function up()
	{
		$statement = Doctrine_Manager::getInstance()->connection();
		$results = $statement->execute("ALTER TABLE  `partenaire_programme` ADD  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST");
    }

    public function down()
    {
    }
}
