<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version67 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('partenaire_logo', 'partenaire_logo_partenaire_id_partenaire_id', array(
             'name' => 'partenaire_logo_partenaire_id_partenaire_id',
             'local' => 'partenaire_id',
             'foreign' => 'id',
             'foreignTable' => 'partenaire',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('partenaire_logo', 'partenaire_logo_partenaire_id', array(
             'fields' => 
             array(
              0 => 'partenaire_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('partenaire_logo', 'partenaire_logo_partenaire_id_partenaire_id');
        $this->removeIndex('partenaire_logo', 'partenaire_logo_partenaire_id', array(
             'fields' => 
             array(
              0 => 'partenaire_id',
             ),
             ));
    }
}
