<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version66 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('partenaire_logo', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'partenaire_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '4',
             ),
             'src' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '128',
             ),
             'href' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->removeColumn('partenaire', 'logo');
    }

    public function down()
    {
        $this->dropTable('partenaire_logo');
        $this->addColumn('partenaire', 'logo', 'string', '128', array(
             ));
    }
}
