<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version69 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('partenaire', 'page_title', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('partenaire', 'page_title');
    }
}