<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version70 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('partenaire', 'title', 'string', '4000', array(
             ));
    }

    public function down()
    {

    }
}