<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version71 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('mailing_list', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'email_address' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'unique' => '1',
              'length' => '255',
             ),
             'is_newsletter' => 
             array(
              'type' => 'boolean',
              'notnull' => '1',
              'default' => '1',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addColumn('filleul', 'is_newsletter', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '0',
             ));
        $this->addColumn('log_coupon', 'is_newsletter', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '1',
             ));
        $this->addColumn('preinscription', 'is_newsletter', 'boolean', '25', array(
             'notnull' => '1',
             'default' => '1',
             ));
        $this->changeColumn('profil', 'is_newsletter', 'integer', '1', array(
             'notnull' => '1',
             'default' => '1',
             ));
    }

    public function down()
    {
        $this->dropTable('mailing_list');
        $this->removeColumn('filleul', 'is_newsletter');
        $this->removeColumn('log_coupon', 'is_newsletter');
        $this->removeColumn('preinscription', 'is_newsletter');
    }
}