<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version72 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('article_translation', 'accroche', 'clob', '65535', array(
             ));
    }

    public function down()
    {

    }
}