<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version75 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('gallery', 'gallery_category_id_category_id', array(
             'name' => 'gallery_category_id_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'category',
             ));
        $this->createForeignKey('picture', 'picture_gallery_id_gallery_id', array(
             'name' => 'picture_gallery_id_gallery_id',
             'local' => 'gallery_id',
             'foreign' => 'id',
             'foreignTable' => 'gallery',
             ));
        $this->createForeignKey('gallery_translation', 'gallery_translation_id_gallery_id', array(
             'name' => 'gallery_translation_id_gallery_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'gallery',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('picture_translation', 'picture_translation_id_picture_id', array(
             'name' => 'picture_translation_id_picture_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'picture',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('gallery', 'gallery_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->addIndex('picture', 'picture_gallery_id', array(
             'fields' => 
             array(
              0 => 'gallery_id',
             ),
             ));
        $this->addIndex('gallery_translation', 'gallery_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->addIndex('picture_translation', 'picture_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('gallery', 'gallery_category_id_category_id');
        $this->dropForeignKey('picture', 'picture_gallery_id_gallery_id');
        $this->dropForeignKey('gallery_translation', 'gallery_translation_id_gallery_id');
        $this->dropForeignKey('picture_translation', 'picture_translation_id_picture_id');
        $this->removeIndex('gallery', 'gallery_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->removeIndex('picture', 'picture_gallery_id', array(
             'fields' => 
             array(
              0 => 'gallery_id',
             ),
             ));
        $this->removeIndex('gallery_translation', 'gallery_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->removeIndex('picture_translation', 'picture_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}