<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version74 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('gallery', array(
             'id' =>
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'category_id' =>
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'created_at' =>
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' =>
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' =>
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('picture', array(
             'id' =>
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'gallery_id' =>
             array(
              'type' => 'integer',
              'length' => '4',
             ),
             'src' =>
             array(
              'type' => 'string',
              'length' => '255',
             ),
             ), array(
             'primary' =>
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('gallery_translation', array(
             'id' =>
             array(
              'type' => 'integer',
              'length' => '4',
              'primary' => '1',
             ),
             'title' =>
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'description' =>
             array(
              'type' => 'clob',
              'length' => '65535',
             ),
             'lang' =>
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             'slug' =>
             array(
              'type' => 'string',
              'length' => '255',
             ),
             ), array(
             'indexes' =>
             array(
              'gallery_translation_sluggable' =>
              array(
              'fields' =>
              array(
               0 => 'slug',
               1 => 'lang',
               2 => 'title',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' =>
             array(
              0 => 'id',
              1 => 'lang',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('gallery');
        $this->dropTable('picture');
        $this->dropTable('gallery_translation');
    }
}