<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version76 extends Doctrine_Migration_Base
{

    public function up()
    {
        $this->addColumn('partenaire', 'is_active', 'boolean', '25', array(
            'default' => '1',
        ));
    }

    public function down()
    {
        $this->removeColumn('partenaire', 'is_active');
    }
}