<?php

/**
 * BaseMicropaymentDebitPaymentData
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    up2green
 * @subpackage model
 * @author     Clément Gautier
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMicropaymentDebitPaymentData extends PaymentData
{
    public function setUp()
    {
        parent::setUp();
        
    }
}